### ISSUE TITLE
Can I set the list can't be dropped?

### ISSUE THREAD

**Issue by alexliubj** [marceljuenemann/angular-drag-and-drop-lists#106]
I have one list for accepting the element which dropped here, which I call it original list.
but I don't want the original list can be changed like the source list can not be dropped but can be dragged into others.

**Comment by yagoferrer** [comment]
In the template, you can set `dnd-allowed-type`s containing an array of the allowed types.  Then you mark the items that you don't want to be able to drop with a different type. Does that help? It might help if you provide a JSFiddle.

**Comment by marceljuenemann** [comment]
Just don't use dnd-list on the source list, you can use dnd-draggable without having a dnd-list

**Comment by alexliubj** [comment]
Thanks marceljuenemann, it's a good idea.
