### ISSUE TITLE
Mark all possible destinations.

### ISSUE THREAD

**Issue by yagoferrer** [marceljuenemann/angular-drag-and-drop-lists#107]
When I start dragging the element, but I'm still not over the droppable zone, I would like to add a class or a placeholder to all possible locations where the element can be drop. So that I can indicate all the places where you can drop the element beforehand.

How would you handle this? What changes do you think I need to do?

**Comment by marceljuenemann** [comment]
I think you'll need the dnd-dragstart and dnd-dragend callbacks and then add/remove a CSS class to your root element. Note that dnd-dragend is only in the dev branch and not merged to master, yet.
