### ISSUE TITLE
Dropping Item on empty dnd-list causes jitter

### ISSUE THREAD

**Issue by tugayac** [marceljuenemann/angular-drag-and-drop-lists#110]
Recently, I have run into an issue with the drag-and-drop list where it looks like dragging an item onto an empty dnd-list (attribute on a ul tag) causes unwanted jitter. I was able to reproduce this problem on the [official demo page](http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested) as well. In addition, here's a [GIF showing what the jitter looks like](http://www.gfycat.com/BitesizedOrdinaryFruitfly).

Has anyone encountered this issue before. If so, anyone have an idea how to fix it?

**Comment by tugayac** [comment]
Currently, the issue seems to only happen on Chrome and Safari (not Firefox). Issue seems to lie in the `isMouseInFirstHalf` function, where the offset values are used for the `MouseEvent` ([@ Line 375](https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/master/angular-drag-and-drop-lists.js#L375)) to find the mouse pointer location.

Using the `MouseEvent`'s layerX and layerY values seem to fix this this problem. However, since [layerX and layerY properties of an event are non-standard](https://developer.mozilla.org/en-US/docs/Web/API/UIEvent/layerX), it might be a better idea to use a function that calculates the mouse pointer location. Once such function (and the one I used to fix this issue) is like the following:

```js
function getOffset(event) {
    var el = event.target.offsetParent,
           x = 0,
           y = 0;

    while (el && !isNaN(el.offsetLeft) && !isNaN(el.offsetTop)) {
        x += el.offsetLeft - el.scrollLeft;
        y += el.offsetTop - el.scrollTop;
        el = el.offsetParent;
    }
    x = event.clientX - x;
    y = event.clientY - y;

    return {
        x: x,
        y: y
    };
}
```

**Comment by zorzysty** [comment]
@tugayac I'm experiencing the same jittering in my application for some time, but on the dnd-lists demo everything works correctly. I find it kind of strange.
Is there a way to repair it without interfering with the dnd-lists source code?

**Comment by tugayac** [comment]
I've tested my solution on the latest version of Chrome and Safari. What browser and version are you using?

**Comment by zorzysty** [comment]
@tugayac Chrome 44.0.2403.130 and dnd-lists 1.2

**Comment by tugayac** [comment]
My configuration is the same as yours. Perhaps @marceljuenemann knows what could be going on?

**Comment by zorzysty** [comment]
@tugayac @marceljuenemann I've manage to locate my problem, but I can't figure out how to fix it. I've opened separate issue describing it: https://github.com/marceljuenemann/angular-drag-and-drop-lists/issues/113

**Comment by marceljuenemann** [comment]
This is a CSS problem, it exists because the empty column does not take 100% of the container height, but only has a min-height. If an element is then dragged over the part of the container that is not within the column element, the placeholder is set above the container element. This in turn moves the container to the bottom, which then puts the dragged element back into the column element, therefore moving the placeholder again...

If you manage your columns to take 100% of the height, this problem should disappear.
