### ISSUE TITLE
Flickering on hover when using angular-filter groupBy method with reverse filter

### ISSUE THREAD

**Issue by zorzysty** [marceljuenemann/angular-drag-and-drop-lists#113]
A strange thing is happening. I've got dnd-lists  nested inside ng-repeat filtered using angular-filter method called groupBy:
`ng-repeat="(key, value) in players | groupBy: 'team'"`
 When I also use ["reverse" filter](https://github.com/a8m/angular-filter#reverse) and try to drop an element on the list it starts to flicker making it imposible to drop. This thing doesn't happen when i remove "reverse" filter.

Here are the plunks showing the problem:
http://plnkr.co/edit/f3TnGx1Qdn8GlZ2Y7sar?p=info - without "reverse" (**working correctly**)
http://plnkr.co/edit/Z4APXiqdTr9tSsCIqBnA?p=info - with "reverse" (**not working**)

The only difference betwen the two is in line 18 in index.html.
Is there a way to fix this?

**Comment by marceljuenemann** [comment]
It looks like you want to determine the order in which the elements are displayed yourself, so it doesn't really make sense to use this directive, whose purpose is to let the user determine the order?!

**Comment by zorzysty** [comment]
You got it wrong. Please see the provided plunks to see what's the problem.
Basically dnd-lists are nested inside divs which are displayed by ng-repeat and filtered using groupBy. Not the items in dnd-lists are filtered, but the divs that hold them. It really makes perfect sense and is kind of crucial for my app. 

The issue should be reopened, since the problem still exists.

**Comment by marceljuenemann** [comment]
Sorry, was on mobile and couldn't properly check
