### ISSUE TITLE
Similar to issue 66, dragging from high index to low is causing object to duplicate

### ISSUE THREAD

**Issue by dshep4** [marceljuenemann/angular-drag-and-drop-lists#114]
<ul class="col-lg-12" style="list-style-type: none" dnd-list="slides">
         <li class="file-box" 
                ng-repeat="slide in slides track by $index"
                dnd-draggable="slide" 
                dnd-moved="slides.splice($index, 1)" 
                dnd-effect-allowed="move">
                    
                    <div class="file">
                        <div class="icon">
                            <i class="img-responsive fa fa-caret-square-o-right"></i>
                        </div>
                        <div class="file-name">
                            <table>
                                <tr>
                                    <td width="45%">{{slide.name}}</td>
                                    ....
                                </tr>
                            </table>
                        </div>
                    </div>
                </li>
            </ul>

Slides are represented as an array of similar objects

```
slides: [
    {
        id: 9cab2f20-9217-4eb0-86b3-9ee4f66ad288,
        name: slide3,
        length: 10,
        ....
    },
    ....
] 
```

When I drag and drop an element into a higher index the operation works as expected. If I drag an element into a lower index, the element I dragged slides into the index that it should, the elements in the list shift to the right as they should, but the element that was dragged also remains at its original index and the element that was suppose to assume this position is dropped from the model.

[Issue 66] (https://github.com/marceljuenemann/angular-drag-and-drop-lists/issues/66) was solved by using a list of objects and tracking by $index which I am doing.

**Comment by dshep4** [comment]
Solved by _removing_ track by $index

**Comment by JohannMarx** [comment]
Having the same issue and removing the track by $index is not an option for me, because I need to be able to have duplicates in the list. Any ideas on how to make it work with the track by $index?

**Comment by marceljuenemann** [comment]
You don't need track by $index to have duplicate elements, just make sure angular assigns them a unique $$hashKey. See this discussion:
https://github.com/marceljuenemann/angular-drag-and-drop-lists/issues/96#issuecomment-123630839
