### ISSUE TITLE
Using other HTML elements instead of item

### ISSUE THREAD

**Issue by siddharthsrivastava** [marceljuenemann/angular-drag-and-drop-lists#115]
Hi

I am trying to build a drag and drop form designer. Is it possible to add textboxes, combos, textareas instead of label like items only using this library.
I looked at the code, but couldn't determine how can I use something like "input in list" instead of "item in list".

**Comment by marceljuenemann** [comment]
item is just a variable name, you can set it to whatever you want and it has nothing to do with HTML elements. It's definitely possible to build something like a form designer.

**Comment by siddharthsrivastava** [comment]
Thanks. I am new to JS. After numerous attempts I am unable to see how can make a textbox (or any other html element) appear instead of the label.

**Comment by marceljuenemann** [comment]
See this new demo: http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/types
