### ISSUE TITLE
is it possible to add drag effect (rotate) only for the item in the air ?

### ISSUE THREAD

**Issue by liadlivnat** [marceljuenemann/angular-drag-and-drop-lists#117]
when i use the dndDragging it changes also the existing li
i want to add style just for the item "in the air"

i'm attaching image that explain it better
![untitled](https://cloud.githubusercontent.com/assets/2083527/9227511/995c75c8-411c-11e5-9a5c-3c31534dcbc5.png)

Can someone help?
to be more accurate i'm looking to implement "like trello" effect.

![capture](https://cloud.githubusercontent.com/assets/2083527/9227647/4fe60750-411d-11e5-816a-9c239dfb3043.PNG)

**Comment by marceljuenemann** [comment]
Sure, just use CSS' :not modifier:

    .dndDragging:not(.dndDraggingSource) {
      ...
    }

**Comment by liadlivnat** [comment]
Thanks but it didn't work.

i did the following:

```.dndDragging:not(.dndDraggingSource) {
  width: 322px;
  height: 37px;
  position: relative;
  cursor: pointer;
  padding-left: 10px;
  padding-right: 10px;
  float: left;
    -ms-transform: rotate(6deg);
    -webkit-transform: rotate(6deg);
    transform: rotate(6deg);
}```

**Comment by marceljuenemann** [comment]
Your CSS works when applied to the demo. Make sure its not overwritten by other CSS rules.
