### ISSUE TITLE
Dragleave event

### ISSUE THREAD

**Issue by Blaze34** [marceljuenemann/angular-drag-and-drop-lists#119]
As I found out `dragleave` event case many problems.
In source I found some fix (but it doesn't work).
https://github.com/marceljuenemann/angular-drag-and-drop-lists/blob/master/angular-drag-and-drop-lists.js#L359
I wrote own directive in which calculate real `dragleave` event on dropzone.
May be You get my idea and improve your calculations

```
angular.module('app')
  .directive('xdDragOverClass', function() {
    return {
      restrict: 'A',
      link: function(scope, element, attrs) {

        element.on('dragover', function() {
          element.addClass(attrs.xdDragOverClass);
        });
        element.on('dragleave', function(e) {
          if (element.is(e.target) && !isEventInElement(e.originalEvent || event)) {
            element.removeClass(attrs.xdDragOverClass);
          }
        });
        element.on('drop', function() {
          element.removeClass(attrs.xdDragOverClass);
        });

        function isEventInElement(event) {
          var offset = element.offset();

          return (event.clientX > offset.left) && (event.clientY > offset.top) &&
            (event.clientX < offset.left + element.width()) && (event.clientY < offset.top + element.height());
        }
      }
    }
  });
```

Example using

```
.dropzone dnd-list="items" xd-drag-over-class="xdDragover"
```

Important point is `function isEventInElement`
I use jQuery, but You can rewrite this without it.

I hope it'll help You.

**Comment by marceljuenemann** [comment]
I don't think your approach will work for nested lists?!

**Comment by Blaze34** [comment]
Yes, this is just idea. It's possible to get event.originalTarget and find closest dnd-list, then compare with element

**Comment by marceljuenemann** [comment]
On second thought, you just need to stop propagation in the dragleave event and then this should work for nested list.

I think an improvement would be to use document.elementFromPoint instead of just assuming the whole rectangle belongs to the element. This would account for possible overlays.

**Comment by Blaze34** [comment]
Stop propagation doesn't work (I tried it).

elementFromPoint return to you one element in sortable list, but you need draggable item and sortable list (maybe I didn't understand your idea)

**Comment by marceljuenemann** [comment]
I tried [one approach](https://github.com/marceljuenemann/angular-drag-and-drop-lists/commit/86d2bcdf39dc15dbcc7718e6d5df8550115992e1), but there were still some problems with the placeholder not being removed sometimes. I think in my next attempt, I will traverse through the DOM within dragleave to solve the nested list usecase.

**Comment by marceljuenemann** [comment]
Solved this by using document.elementFromPoint, and then marking an event as processed to resolve the issue with nested lists.
