### ISSUE TITLE
Trouble with multiple functions on drag and IE 

### ISSUE THREAD

**Issue by GBora** [marceljuenemann/angular-drag-and-drop-lists#120]
```
<ul dnd-list="group.list">
        <li ng-repeat="item in group.list" 
        dnd-draggable="item"
        dnd-moved="group.list.splice($index, 1);otherFunction();"
        dnd-effect-allowed="move"
        dnd-selected="exemptedCountries.models.selected = item;"
        ng-class="{'selected': exemptedCountries.models.selected === item}">
        {{item.Name}}
        </li>
</ul>
```
This works on every browser except IE, where the directive simply doesn't work  unless `dnd-moved` is only set to `group.list.splice($index, 1);`.

I've of course tried to wrap the splice and my function in another function and then set only that function to `dnd-moved` but on IE it would never call that function.

**Comment by marceljuenemann** [comment]
Do you also not see the "Item moved" console output in this demo?
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced
