### ISSUE TITLE
Problem when use with ngAnimate lib

### ISSUE THREAD

**Issue by jbfm21** [marceljuenemann/angular-drag-and-drop-lists#121]
Hello, 
if i inject ngAnimate dependency in my application, after i drop an item, this item blink in the source container, this istem is flashing in the source before appear in destination container. 

When i remove this line of code
     $timeout(function() { element.removeClass("dndDraggingSource"); }, 0)

the item stop flashing in the source container, but if i move the item to a invalid place, the item disappears.

**Comment by sgraham3311** [comment]
I can confirm this issue. Having the ngAnimate module causes a delay removing the dragging source if you are using css transitions on the dragging element. This link helped me to disable ng-animate on draggable elements http://stackoverflow.com/a/24542131/5298390. This seems to be the only workaround at the moment.

**Comment by marceljuenemann** [comment]
I think I introduced that problem in #21. I should call `element.removeClass("dndDraggingSource");` right away and in addition also call it inside a $timeout.

**Comment by jbrady89** [comment]
@sgraham3311 +1 for this temporary work around that solved the problem for my specific case.  I ended up giving the dnd list items a unique class name and added a classNameFilter to ignore that particular class.
