### ISSUE TITLE
problem when having the vertical and horizontal dragging at the same time

### ISSUE THREAD

**Issue by AnnaHevelius** [marceljuenemann/angular-drag-and-drop-lists#122]
Hi, thanks for the plugin,
We have a table style list (mix of vertical and horizontal) like in pic.
The amount of horizontal items is depends on window size
![untitled](https://cloud.githubusercontent.com/assets/8040938/9320457/1c424c34-4563-11e5-9ca7-288540158490.png)

Currently dnd-horizontal-list=false, and it doesn't work properly for horizontal dragging, the issue is more obvious when dragging the item to the right side (e.g. 5 to 6).
Could you please add possibility to have dragging functionality for vertical and horizontal dragging at the same time

**Comment by marceljuenemann** [comment]
This sounds like a hard problem and is probably not feasible to implement in the directive. I see no way to reliable determine the correct position to insert.

**Comment by marceljuenemann** [comment]
I think this works reasonably well in the advanced demo, I don't think it's worth to add more complicated logic.
