### ISSUE TITLE
2 column in "From" list

### ISSUE THREAD

**Issue by mememol2007** [marceljuenemann/angular-drag-and-drop-lists#124]
I am using Simple list. I want the drag list(List A) to show 2 column for the drag items as shown in attached image. 
![dd2column](https://cloud.githubusercontent.com/assets/13956785/9458845/39aae402-4b26-11e5-86b4-28ec2cceb2fb.jpg)
Does css should be used?

**Comment by marceljuenemann** [comment]
Yes, that sounds like a CSS problem, doesn't really have anything to do with the directive. If you need help with that, stackoverflow might be a better forum.
