### ISSUE TITLE
Dragging dates or objects with dates causes <input type="date"> to break

### ISSUE THREAD

**Issue by jjoedouglas** [marceljuenemann/angular-drag-and-drop-lists#128]
Due to serializing a date to JSON and deserializing it does not result in a Date object.  This causes angular to complain about models bound to `<input type="date" />`.

See [plunker here](http://plnkr.co/edit/tdKQd4cUHBQimdWzWV9A?p=info)

**Comment by marceljuenemann** [comment]
I've never used type=date, but it looks like it works with strings as well. If not you will need to do the conversions yourself, since you can't transfer Date objects with json.
