### ISSUE TITLE
Trouble persisting data with Firebase

### ISSUE THREAD

**Issue by brockclayton403** [marceljuenemann/angular-drag-and-drop-lists#136]
I got the data model load in a similar structure as the demonstration json file. And I got the ng-repeat ="task in list.tasks" retuning data. However, I cannot get the data to persist back to firebase. I suspect it is because of firebase's requirement to add uid's when pushing data.

Here is what the data structure in firebase looks like:
![image](https://cloud.githubusercontent.com/assets/6024767/9866239/50c44b40-5b1d-11e5-8039-a9b51457bf6c.png)

I know this is probably outside of the realm of supporting, and I suspect that I have not provided enough information, any more information you could provide would be greatly appreciated.

Thanks,

Brock

**Comment by jaymanned** [comment]
Brock, did you find out the reason?

**Comment by ibrychgo** [comment]
I'm about to embark on a similar quest (draggable lists using angular and firebase) and this post caught my attention as I was eyeing this library as a potential solution for the UI. Brock, did you figure this out?

**Comment by brockclayton403** [comment]
No I never did, but I was able to use the template for a rather nice interface without the drag and drop part. I may revisit it in the future.

Brock

**Comment by marceljuenemann** [comment]
I have no clue about firebase, but it sounds like you just have to keep the UIDs updated? That is definitely possible by doing the updates in the dnd-drop callback.
