### ISSUE TITLE
Bootstrap Modal Breaks, display none and class "in" do not get applied

### ISSUE THREAD

**Issue by spencercree** [marceljuenemann/angular-drag-and-drop-lists#137]
I have a list that is created with ngRepeat, and each list has a modal that is specific too it. When I added this directive the modal stopped appearing as intended. I've noticed that the inline style "display:none" does not appear to begin with and then does not change to "display:block" and the class "in" is also not applied.

**Comment by spencercree** [comment]
dnd-selected="models.selected = section" --> the issue I have found is with this

**Comment by marceljuenemann** [comment]
I guess this is a problem with your HTML/CSS, don't see what this has to do with the directive. If you create a demo I might take a look, but otherwise it's hard to say what's wrong.
