### ISSUE TITLE
Dragging is overwhelming callbacks queue on the JS VM

### ISSUE THREAD

**Issue by gkohen** [marceljuenemann/angular-drag-and-drop-lists#139]
Version: 1.3.0
Dragging can be sometime calling the onDrag over a 100 times per second, thus overwhelming the VM.
It's best practice to have use cases like these, debounced. You can see something similar done with field value updates in Angular 1.3.
The flooding of calls to the VM causes pending commands to be delayed by up to 2-3 seconds.

**Comment by marceljuenemann** [comment]
The HTML5 spec says that browsers should trigger the drag events only "every 350ms (±200ms)". If a browser triggers them every 10ms I'd consider that a browser bug. In which browsers did you observe this?
