### ISSUE TITLE
Items are missing on drop

### ISSUE THREAD

**Issue by madanv** [marceljuenemann/angular-drag-and-drop-lists#14]
Hello, I observed that the items are sometimes missing after drop into a different list from its parent. Could some one help me resolving it.

**Comment by manindr** [comment]
Hi,
I'm sorry for bothering you guys but i'm also facing this issue even with the latest code. Do i need to do something by myself to fix this issue or library take cares of it by itself now?

      <ul dnd-list
          dnd-drop="dropPageCallback(index,callback)"
          dnd-allowed-types="['page']">
        <li ng-repeat="page in canvas.pages track by page.id"
            dnd-draggable="null"
            dnd-callback="$index"
            dnd-effect-allowed="move"
            dnd-type="'page'">
          <div>
            <button draggable="true"
                    title="{{page.title}}"
                    ng-click="selectPageAndSection(page)"
                    ng-bind="page.title"></button>
          </div>

          
          <ul 
              dnd-list
              dnd-drop="dropSectionCallback(index,callback)"
              dnd-allowed-types="['section']">
            <li ng-repeat="section in page.sections track by section.id"
                dnd-draggable="null"
                dnd-callback="$index"
                dnd-effect-allowed="move"
                dnd-type="'section'">
              <div>
                <button draggable="true"
                        data-tid="page-list-section-menu-item-{{section.id}}"
                        title="{{section.title}}"
                        ng-click="selectPageAndSection(page, section)"
                        ng-bind="section.title></button>
              </div>
            </li>
          </ul>
        </li>
      </ul>
  
JS code


      public dropPageCallback(toIndex: number, callback: Function): boolean{
              const fromIndex = callback();
              //move page
            return true;
      }

       public dropSectionCallback(toIndex: number, callback: Function): boolean{
                 const fromIndex = callback();
                //move section 
               return true;
        }

Any help would be really appreciated. Thanks.
