### ISSUE TITLE
feature request: distinguish wether element is being moved or copied

### ISSUE THREAD

**Issue by santialbo** [marceljuenemann/angular-drag-and-drop-lists#144]
First of all thanks for developing this library, it's awesome and works really well!

It would be useful if we could get additional classes on the source element to distinguish wether it's being copied or just moved.

My usecase is the following:
I'm currently doing a `display: none` on `.dndDraggingSource`, so that it looks like the element has been pulled out of the list. However when I'm copying the element instead of just moving it (pressing alt on a mac) it looks weird when dropped since visually there are 2 elements that appear on the list (one being the source that was never removed). If I could distinguish both cases I could apply different styles and create a better user experience.

**Comment by marclazell** [comment]
+1

**Comment by marceljuenemann** [comment]
It's not possible with the HTML5 API. You could listen to mouse move events and check whether the ctrl/alt key is pressed, but this won't work when dragging outside the browser window.
