### ISSUE TITLE
Please publish to npm

### ISSUE THREAD

**Issue by dambrosiomike** [marceljuenemann/angular-drag-and-drop-lists#146]
Thank you very much for putting this library together. I'd like to leverage it in a project, but due to factors beyond my control, our automated system can only pull down packages that are published in the NPM repository. If it is possible, can the HEAD of master be published to npm with a version that includes the latest change (the addition of a main field in package.json). Thanks again!

**Comment by luizstacio** [comment]
Please publish to npm!

**Comment by NukaPunk** [comment]
I found it [here](https://www.npmjs.com/package/angular-drag-and-drop-lists).

**Comment by marceljuenemann** [comment]
1.4.0 is published to npm now
