### ISSUE TITLE
Is it possible to drop on a container, not on a list

### ISSUE THREAD

**Issue by jaymanned** [marceljuenemann/angular-drag-and-drop-lists#149]
I've a use case where items -files- can be dropped into files lists but also directly into folders. An some of these folders do not have an underlying list to receive the item. Is there a way to drop not only into lists nested into containers but directly into a listless container that cannot show drop placeholders? 

Note: To make it work, these containers would need to provide visual cues that they are valid targets too, a CSS style would suffice.

**Comment by jaymanned** [comment]
Hi again. Has anybody created something similar? Any workarounds or any fork out there?

**Comment by marceljuenemann** [comment]
It's definitely possible, you could treat the container as a list with max. 1 element. You can use a custom placeholder element for styling. Or hide it completely and use the dragover callback.

**Comment by jaymanned** [comment]
Hum, I think I'll give it a try. If it doesn't work for me I'll probably end up writing an additional directive. Thanks

**Comment by jaymanned** [comment]
The issue I'm having is that the drop area is always inserted as a new `<li>` element. I need to drop on existing `<li>` elements (e.g. the individual folders in a list of folders). Any suggestions?

**Comment by zatziky** [comment]
Here is the controller for the drop on the container's title tag:

` function ListTitleController($element, moveItemService) {
        var self = this;

        self.cssClass = {titleDragover: 'title-dragover'};

        self.$postLink = $postLink;

        function $postLink() {
            $element.on('dragover', function (event) {
                event.preventDefault();
            });

            $element.on('dragenter', function (event) {
                event.preventDefault();
                if (_isMovingSameDndType()) {
                    return;
                }
                if (_itemCanBeDropped()) {
                    $element.addClass(self.cssClass.titleDragover);
                }
            });

            $element.on('dragleave', function () {
                if (_isMovingSameDndType()) {
                    return;
                }

                $element.removeClass(self.cssClass.titleDragover);
            });

            $element.on('drop', function () {
                if (_isMovingSameDndType()) {
                    return;
                }

                $element.removeClass(self.cssClass.titleDragover);
                if (_itemCanBeDropped()) {
                    self.onDrop();
                } else {
                    moveItemService.cancelMove();
                }
            });

        }

        function _isMovingSameDndType() {
            return self.item.dndType === moveItemService.getDndType();
        }

        function _itemCanBeDropped() {
            return _.includes(self.item.allowedTypes, moveItemService.getDndType()) && !self.isExpanded;
        }
    }`


The html has this structure:

```
<container>
  <droppable-title></droppable-title>
 <item ng-repeat="i in $ctrl.items"></item>
</container>
```
