### ISSUE TITLE
Can't make it work on Safari (latest, desktop)

### ISSUE THREAD

**Issue by tplaindoux** [marceljuenemann/angular-drag-and-drop-lists#15]
For some reason it just does nothing.

I can click & hold, but when I release, the item go back to its original position.

Working well on chrome & firefox.

Any idea?

**Comment by abhisb** [comment]
The same issue exists for me while using with WKWebView. But it's working fine in Safari(11.0.2). I'm wondering how to solve this in WKWebView. Is this issue related to the webkit version of WKWebView?
