### ISSUE TITLE
How to determine the target container?

### ISSUE THREAD

**Issue by ayaniv** [marceljuenemann/angular-drag-and-drop-lists#154]

**Comment by marceljuenemann** [comment]
No description given.

**Comment by flick36** [comment]
i believe, he is asking if there's a way to know the list content on wich you dropped an item, i'm triying to figure how to do it as well, cause i don't need to duplicate a list item y it already exists in the targeted list, Any idea on how to do that?

**Comment by marceljuenemann** [comment]
The list is in the scope of your target dnd-list, so just pass it into your callback, e.g.
`<div dnd-list="myList" dnd-drop="onDrop(myList, item)">``
where item comes from the directive and myList comes from your scope.
