### ISSUE TITLE
Can still drag when dnd-disable-if = true in some cases

### ISSUE THREAD

**Issue by tcauduro** [marceljuenemann/angular-drag-and-drop-lists#159]
I'm having an issue with drag-able items still being dragged even if their dnd-disable-if= true.
Dragging the parent element itself is not possible, but say I have a span tag inside of a parent div.  I can highlight the span element content and then proceed to drag the div container as if nothing was disabled.

I then tried to add some css rules to the div: user-select:none.   Now I can't highlight that span tag content (which isn't a solution as my users need to highlight that content occasionally) but I can still highlight the whole parent div section (it looks like it's highlighting the background) and then move the div as if it wasn't disabled again.

Here's a JSFiddle example: https://jsfiddle.net/c16586nj/8/
The reds are not to be drag-able, greens can.  I've disabled user-select on the inner span tags, but if you highlight the a whole row, you can move any of the disabled items.

**Comment by marceljuenemann** [comment]
I should probably check for dnd-disabled-if in the dragstart handler again (or just check the draggable attribute)
