### ISSUE TITLE
It's not possible to select text on input types with the dnd-nodrag on Windows 10 IE Edge

### ISSUE THREAD

**Issue by warrenbailey** [marceljuenemann/angular-drag-and-drop-lists#160]
If you add the dnd-nodrag to input elements (i.e. text areas and text inputs) it's not possible to highlight the text using a mouse. It's also difficult to click into the input box. This seems to affect IE edge on Windows 10. 

It's easily apparent in the demo as well:
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/types

**Comment by warren-methods** [comment]
Also affects IE 11 on windows 8.1

**Comment by mmaszkiewicz** [comment]
This is due to a bug in IE:

https://connect.microsoft.com/IE/feedback/details/927470/ie-11-input-field-of-type-text-does-not-respond-to-mouse-clicks-when-ancestor-node-has-draggable-true#tabs

There's a very impractical work-around for it: double-click in the input.

**Comment by cannehag** [comment]
Seriously? Is that the workaround you give to users of your product? :)

**Comment by mmaszkiewicz** [comment]
Neither of us contribute to this project @cannehag. Someone might find that feedback useful - when fixing this, maybe?

**Comment by Jshyu523** [comment]
+1 I am also experiencing this problem. Has anyone had any luck with a workaround?

**Comment by Goddak** [comment]
I posted something that may help with this issue [here](https://github.com/marceljuenemann/angular-drag-and-drop-lists/issues/403#issuecomment-335814655)
