### ISSUE TITLE
Sample code not working

### ISSUE THREAD

**Issue by louiealmeda** [marceljuenemann/angular-drag-and-drop-lists#161]
I cant make this sample code to work:
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/simple

I think the sample code and the output does not match?

**Comment by louiealmeda** [comment]
Sorry my bad

**Comment by meenakshijha** [comment]
@louiealmeda Even I cant make the sample demo of simple list work. Not sure what I am missing here. Can you throw some light what exactly you were missing?

**Comment by louiealmeda** [comment]
@meenakshijha sorry I don't recall that specific solution, But I do remember that I had to include the element or controller that contains the example which is not shown in the demos itself. That's why it is indeed confusing
