### ISSUE TITLE
functions inside object removed after drag

### ISSUE THREAD

**Issue by ayaniv** [marceljuenemann/angular-drag-and-drop-lists#163]
I have a model that hols an array of objects.
I use angular-drag-and-drop-lists in order to drag items in the repeater.

somehow, the functions disappers in the 'transferredObject'.
how to overcome that?

**Comment by kvetis** [comment]
Probable cause:
The object is serialized and deserialized and it is not even the same object after that.
Solution I suggest:
Write your own `dnd-drop` callback and handle the remove insert logic by yourself.

**Comment by ayaniv** [comment]
after digging the dnd sourcecode I saw that angular.toJson removes the functions in the javascript's object. Probably it just ignores them as functions not supposed to be part of a JSON. I'll add those functions in the callback funcion.
