### ISSUE TITLE
Simple Drag-Drop between 2 divs inside a parent div

### ISSUE THREAD

**Issue by simon-nguyen** [marceljuenemann/angular-drag-and-drop-lists#164]
First of all, this is the most awesome component I have found so far!
The question is. I have a page with a main div element. And inside, I have two divs, each contains a directive.
```
<div class="container" dnd-list>
    <div class="row" dnd-draggable>
        <directive-a></directive-a>
    </div>
    <div class="row" dnd-draggable>
        <directive-b></directive-b>
    </div>
</div>
```

How can I make these two divs swap-able inside the containter using your library? I have tried but failed...

**Comment by shoebsd** [comment]
Hi, I am trying to do a similar kind of thing. As per the examples on <li>'s are draggable. Its not working for div. I have a select tag inside the div which I want to drag and drop in the container

**Comment by simon-nguyen** [comment]
@shoebsd I've made it work using dragular. I still have a plunker for simple drag-drop div. Please check it out if it suits you http://plnkr.co/edit/jwoB26vRX8weIrT8ZDyD?p=preview

The reason I've chosen dragular because I can interact with my directive after drag-drop them. My plunker only support drag-drop only... after that, you can't click on the buttons.
