### ISSUE TITLE
publish 1.3.0 to npm

### ISSUE THREAD

**Issue by joeldenning** [marceljuenemann/angular-drag-and-drop-lists#165]
Are you waiting on anything to publish 1.3.0 to npm? If not, could you do that? Right now I'm using a forked version of this repo because I needed a bug fix that's in 1.3.0, and I can't get 1.3.0 without forking :)

**Comment by marcelorl** [comment]
"napa": {
    "angular-drag-and-drop-lists": "marceljuenemann/angular-drag-and-drop-lists"
  }

You can use napa to download this version...I just did it.

**Comment by marceljuenemann** [comment]
1.4.0 is published to npm

**Comment by marcelorl** [comment]
great
