### ISSUE TITLE
demo code, not able to drag new elements

### ISSUE THREAD

**Issue by ehijzen** [marceljuenemann/angular-drag-and-drop-lists#166]
I'm using bootstrap 3.3 and the bootstrap.min.js did not have 
.btn.disabled, .btn[disabled], fieldset[disabled] .btn {
    cursor: not-allowed;
    pointer-events: none;
    opacity: .65;
    filter: alpha(opacity=65);
    -webkit-box-shadow: none;
    box-shadow: none;
}
The demo uses bootstrap 3.1. 
Without this css, the demo code did not work correctly (not able to drag the new elements)

**Comment by marceljuenemann** [comment]
The demos are there to demonstrate the features of the directive and how to use them, the demo code is not meant to be copy & pasted and magically work in your app.

**Comment by seonghuhn** [comment]
Thanks for the reply. However for many of us it's helpful to use the demo code as a starting point for our apps.

Would appreciate if you could at least confirm what @ehijzen said is correct and why such CSS is needed to make the demo work locally.

Thanks!
