### ISSUE TITLE
Drop - inserted - dragstart - etc... dont fire

### ISSUE THREAD

**Issue by marcelorl** [marceljuenemann/angular-drag-and-drop-lists#167]
I have few callbacks that I managed to work.

But these important ones like: drop, inserted, dragstart dont.

```
<ol dnd-list="supplier.linkedProducts">
   <li dnd-draggable="p"
       dnd-dragstart="logEvent('Started to drag an item', event)"
       dnd-dragend="logEvent('Drag operation ended', event)"
       dnd-inserted="logEvent('Element was inserted at position ' + index, event)"
       dnd-effect-allowed="copyMove"
       ng-repeat="p in supplier.linkedProducts">
            <div>
               {{p.name}}
            </div>
            <div>
               {{p.price}}
            </div>
            <div class="clearfix"></div>
    </li>
</ol>
```

```
vm.logEvent = function(message, event) {
            console.log(message, '(triggered by the following', event.type, 'event)');
            console.log(event);
};
```
It just makes no sense, once the examples on the example page are working smoothly.

Anyone has any idea what I'm doing wrong?

I'm using the version 1.3.0

Thanks.

**Comment by marceljuenemann** [comment]
Drop and inserted are callbacks for the list, not for the elements, so they must be on the ol

**Comment by marcelorl** [comment]
i'm so ashamed, it works now.

Did I miss something in the documentation?

Could this information be added?


Anyways, thanks for the fast reply. Awesome package.

**Comment by marceljuenemann** [comment]
I mean the documentation is split into dnd-list and dnd-draggable, and the callbacks are described below the appropriate directive, so I think it's fine as it is.
