### ISSUE TITLE
draggable + contenteditable

### ISSUE THREAD

**Issue by claudio-destro** [marceljuenemann/angular-drag-and-drop-lists#171]
Hi guys,

I've used your lib in conjunction with a custom-made contenteditable directive:

`<div dnd-draggable ...>
	...
		<div contenteditable ...>
		</div>
	...
</div>`

I know that "contenteditable" and "draggable" attributes are somehow incompatible, but there is a problem with the "selectstart" event in IE:

*it is not disabled when dndDisableIf is set, thus the effect under IE 11 is that the element is still draggable even when draggable="false".*

Obviously I monkey patched my code, but I think some changes should be done even by you :)

editor.parents('[draggable="true"]').off('selectstart');

Kind regards
Claudio Destro

**Comment by marceljuenemann** [comment]
The problem of dragging while dnd-disable-if is true should be fixed in 1.4.0 by this commit:
https://github.com/marceljuenemann/angular-drag-and-drop-lists/commit/ca1491e057663fd0abe1fa85dfe29d07d95b0bde

Can you verify?
