### ISSUE TITLE
Problems styling the dragging source

### ISSUE THREAD

**Issue by yagoferrer** [marceljuenemann/angular-drag-and-drop-lists#174]
It seams that the class `.dndDragging` gets applied to the element you are dragging but also to the original dragging source. Although the dragging source has the class `.dndDraggingSource` it makes it difficult to style the dragging source because inherits from both classes. It would be nice if the class `.dndDragging` gets only applied to the element that you are dragging and not the dragging source.

**Comment by marceljuenemann** [comment]
This is not possible because the element you are dragging is a copy of the dragging source element. It's created by the browser with all the same CSS classes applied. However, you can easily style the element being dragged with the not-selector: .dndDragging:not(.dndDraggingSource)

**Comment by yagoferrer** [comment]
thank you @marceljuenemann! I'll use the not-selector!
