### ISSUE TITLE
Add "Can't-Add-To-List Message" Functionality on Dragover

### ISSUE THREAD

**Issue by MalleusMalefic** [marceljuenemann/angular-drag-and-drop-lists#175]
I have a few different lists that, depending on some other settings, will or will not accept certain dnd-types. I would like to display some sort of notification to the user why they can't add certain items to certain lists as they drag the item over the un-accepting list. I'm using Bootstrap's "popover" functionality to display notifications.

Does anyone have any idea how to accomplish this?

**Comment by marceljuenemann** [comment]
Instead of using dnd-allowed-types, you have to write your own dnd-dragover callback that shows the message and returns false if the type is not allowed.
