### ISSUE TITLE
disable-if + able to sort items

### ISSUE THREAD

**Issue by mrbormeth** [marceljuenemann/angular-drag-and-drop-lists#176]
Hey :)

First the plugin ROCKS! 
Thx for doing a simple working drag/drop plugin without jQuery!

Thou I got one question:
"dnd-disable-if" disables the list as it should so nothing can be moved to it. 
But I would like to sort what is already in the list, how can I make a workaround for that?

**Comment by marceljuenemann** [comment]
hmm, maybe take a look at dnd-type and dnd-allowed-types? Other then that you could also set some global state on dnd-dragstart and check it on dnd-dragover, i.e. prevent the drop if it doesn't come from the same list.
