### ISSUE TITLE
Drag handle inside a dnd-nodrag container

### ISSUE THREAD

**Issue by Cidro** [marceljuenemann/angular-drag-and-drop-lists#178]
Is it possible to have a drag handler inside a container with the dnd-nodrag attribute?

**Comment by marceljuenemann** [comment]
No, but you could have a drag handler outside the dnd-nodrag, and then position it with CSS so that it is displayed inside the dnd-nodrag. Hope that helps.

**Comment by nickiowaspain** [comment]
How is it that in your Item types demo where you have your drag handler inside your dnd-nodrag container?
