### ISSUE TITLE
Pass Item being Dragged on dnd-dragover event

### ISSUE THREAD

**Issue by jtolentino-dev** [marceljuenemann/angular-drag-and-drop-lists#180]
Hi, I'm using your plugin in an application that I'm developing and I'm trying to implement a max nesting of draggable divs.

What I did was utilize the dnd-dragover event handler to check how many nested parent divs do the target div have and allow or prevent it based on a certain number.

I've made that one work, but the problem is when I'm drag-n-dropping a div which already has nested divs inside of it. I was thinking of checking the item being passed to see if it has children divs but I found out that it is not being passed.

(ex. let's say max nesting is 3, if I drag a div with a child and grandchild to a 2-level nested div, it will allow it since I can't account for the item being dragged-n-dropped)

Any other way I can accomplish this?

Below is my code:

            $scope.checkContainerLevel = function (event, index, item, type) {
                var allowElementDrop = true;

                if (type == 'section') {
                    var parentContainers = $(event.currentTarget).parents();
                    //TODO: insert check item child nesting level here

                    var containerlevel = 0;

                    for (var index = 0; index < parentContainers.length && containerlevel < 3; index++) {
                        if (parentContainers[index].attributes['container-section'] &&
                            parentContainers[index].attributes['container-section'].nodeValue == 'true') {
                            containerlevel++;
                        }
                    }

                    if (containerlevel < 3) {
                        allowElementDrop = true;
                    } else {
                        allowElementDrop = false;
                    }
                }

                event.stopPropagation();
                return allowElementDrop;
            }

**Comment by marceljuenemann** [comment]
For security reasons the HTML5 API does not allow us access to the element data on dragover, because we might be dragging from a different application. So the only way to do this is with some global state, e.g. on dragstart event you set a variable to the number you need, and then you read it out during dragover.
