### ISSUE TITLE
dnd-drop objects/hashes instead of arrays

### ISSUE THREAD

**Issue by dbounds** [marceljuenemann/angular-drag-and-drop-lists#181]
My product has several ng-repeated lists based on objects, not arrays. There are a number of reasons why this is the case, the main one is the performance characteristics when accessing a particular object throughout the app, outside of the ng-repeat.

I've been trying to identify the appropriate way to manually handle insertion of the dropped object into the list but have not found a good solution given the lifecycle of events.

**Comment by marceljuenemann** [comment]
There isn't really a good way to perform the insertion manually at the moment, but you could do the insertion in the dnd-drop callback. You will need to return an object though, that then gets inserted by the directive. If you want to get really hacky you could use dnd-inserted as well and manipulate the list after the object was inserted.

Anyways, I should modify the dnd-drop callback to allow manual insertion.

**Comment by marceljuenemann** [comment]
You can now return true in dnd-drop to do the insertion yourself.
