### ISSUE TITLE
Drag And Drop in RobotFramework

### ISSUE THREAD

**Issue by henrichsson** [marceljuenemann/angular-drag-and-drop-lists#182]
Are there any know problems with Drag And Drop within Robot Framework? I am trying to write a test which should drag an element to a specific "placeholder" but no way to do it! Found many solutions on internet but none of them worked?? Please refer to
https://github.com/hmalphettes/robotframework-selenium2library-extensions/issues/1

**Comment by marceljuenemann** [comment]
Testing drag and drop with Selenium seems like a big pain to me. I'd love to have Selenium tests for this directive to automate all the manual testing I have to do for a new version, but I doubt it's actually possible to write tests that behave exactly like the browsers. For example, in this case it looks to me like the dragover event is never fired?! Anyways, I think we are out of luck with this.
