### ISSUE TITLE
Is there a way to make this work with dropping files from your Finder?

### ISSUE THREAD

**Issue by guikubivan** [marceljuenemann/angular-drag-and-drop-lists#183]

**Comment by villesau** [comment]
It seems that this library serializes the file object os that the object looses some data, which is not good for files. If serialization would somehow be possible to avoid, i think it would fix this issue. Its a real problem to me as well.

**Comment by marceljuenemann** [comment]
I'm not sure what you expect to happen when you drag a file into this directive's dropzone? The files API is quite different and there are other directives that help with this (although it's not really hard). This directive is mainly about sorting (nested) lists, so handling files is out of scope.

**Comment by villesau** [comment]
uh, what about sorting list of files? It's not about handling files, just about sorting list of them.  @marceljuenemann

**Comment by marceljuenemann** [comment]
I have hard time imagining a use case for this. So your application requires the user to drop file objects into your dropzone, then you generate a list from those and want to make it sortable?!

**Comment by villesau** [comment]
Exactly. I'm using ngf-fileupload for the drag n' drop and upload. After drag n' dropping the files (to the browser), i have files X, Y and Z. Anyhow it might be wrong order, and they need to be in order Z, X and Y, for example. This is where i would need angular-drag-and-drop-lists. Just to sort the files dropped in the browser. In this case the actual files are uploaded, but i still have thumbnails in the browser, and i still need to tell the actual order of images to the server.

**Comment by guikubivan** [comment]
@marceljuenemann I was able to use another library to deal with dropping files and it just adds it to the end of the array. However, I am seeing what @villesau describes, where data is lost when sorting a list. I've seen this twice, once where I had a File in an attribute of an Object. The other where I had a [Resource object ](https://docs.angularjs.org/api/ngResource/service/$resource). Once dropped into the list, the Object had lost the files in the former and in the latter, the item copied was no longer a Resource, but just a plain old Object (so couldn't call any $save or custom prototype functions).

**Comment by marceljuenemann** [comment]
Ok, I understand the problem now, as you said earlier this is due to serialization. Unfortunately, there is no way around serializing the object with the HTML5 API. (Well, for drops inside the same document we could save the object in a global variable, but then again changing this would break tons of users of this directive.)

As a workaround, you could store the file objects in a global object and only pass around a key to them.
