### ISSUE TITLE
[suggestion] Drag available only by the handler

### ISSUE THREAD

**Issue by tuliomir** [marceljuenemann/angular-drag-and-drop-lists#187]
It would be nice if there was a way to specify which area of the `<li>` element should be available for dragging - something like an inside div with CSS `class="handler"`.

In the [Item Types demo example](http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/types), for instance, the drag action could be available only on the `":::"` part of the element. Clicking and holding anywhere else could act as a simple click or text selection.

**Comment by szaaman** [comment]
+1

**Comment by onigetoc** [comment]
+1

**Comment by zygimantaskazlauskas** [comment]
+1

**Comment by marceljuenemann** [comment]
Well, you can already achieve the exact same thing with the dnd-nodrag directive, simply add an element with dnd-nodrag that fills the entire parent element (with position: absolute or so). I shall update the demo to demonstrate this.

**Comment by RSUN** [comment]
@marceljuenemann Instead of a workaround such as above, it would be very convenient to specify a handler element such as a `dnd-handle` attribute.

**Comment by marceljuenemann** [comment]
So far I mainly opposed this because I didn't know of a clean implementation, but #179 actually has some good ideas that require little code, so I'll probably add a dnd-handle directive in one of the next versions.

**Comment by marceljuenemann** [comment]
The new release 1.4.0 now has a dnd-handle directive

**Comment by youseeus** [comment]
This doesn't work properly. You cant select the text on Firefox 52ESR and IE11
