### ISSUE TITLE
Add dragged item to dndPlaceholder scope

### ISSUE THREAD

**Issue by bmsq** [marceljuenemann/angular-drag-and-drop-lists#189]
I'd like to be able to use the currently dragged item from within the dndPlaceholder template.

**Comment by marceljuenemann** [comment]
This sounds like a valid feature request. However, I think it's not something many people want to do and there are workarounds for it. In order to keep the directive small, I'll will only reconsider this if it is a popular feature request.

**Comment by marceljuenemann** [comment]
You can now use dnd-callback to pass the item value to dnd-dragover. From there you can just set the value on your scope and use it from the placeholder.
