### ISSUE TITLE
problem with dynamic data binding

### ISSUE THREAD

**Issue by shalinl** [marceljuenemann/angular-drag-and-drop-lists#194]
the drag and drop js is working well with static json values but not in the dynamic data. I have fetched the values from the database via Httpservice and given to the nested demo controller. But the Drag and drop function is not working properly while giving the data dynamically.

**Comment by marceljuenemann** [comment]
You really did not provide enough details to get a helpful answer. There is no such thing as "dynamic data" and "static data" in JavaScript, an object is an object and a string is a string. You can see in the demos that the directive works with data manipulated at runtime as well.
