### ISSUE TITLE
How to get the parent id from dropped element 

### ISSUE THREAD

**Issue by shalinl** [marceljuenemann/angular-drag-and-drop-lists#197]
I have integrated this plugin in my application. Now, the problem is while dropping a li into another ul, how can i get the index of the parent ul in which the li is dropped.

**Comment by marceljuenemann** [comment]
From a software design point of view, I'd say the li element should be agnostic to which ul it is in, and the controller of the ul element should take care of everything when a new li is dropped. Anyways, there are lots of possibilities to do this (not that I know what exactly you want to do), but you could expose the ID or a callback on the scope of the ul element, which will then be inherited on the li's scope.
