### ISSUE TITLE
firefox issue for input elements inside of dnd-draggable

### ISSUE THREAD

**Issue by ayaniv** [marceljuenemann/angular-drag-and-drop-lists#199]
cant select text inside input texts in Firefox.
also, cant use mouse to place the cursor in specific place inside the input element.

try to select text with your mouse using FF in the following link:
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/types

**Comment by gummdy** [comment]
This is the same core problem talked about in issue #127

**Comment by marceljuenemann** [comment]
Duplicate of #127
