### ISSUE TITLE
Preserve element's last position (and it's placeholder on its last place) when dragging off the container

### ISSUE THREAD

**Issue by alyrik** [marceljuenemann/angular-drag-and-drop-lists#202]
There is should be a way to handle jumps and flickering when the dragging element is being dragged off its container (but still not dropped). As a possible solution: when element is being dragged off the container its placeholder should remain on its latest place but not disappear.

**Comment by nisr19** [comment]
I have the same issue, how can we resolve it?

**Comment by marceljuenemann** [comment]
I'm not exactly sure I know which situation you are talking about, but showing the placeholder after leaving the dropzone is problematic. The placeholder is an indication to the user that when they let go of the element, this is the position it will be inserted to. If the placeholder is still shown, but the element is not actually inserted, it would be confusing for the user.
