### ISSUE TITLE
get the drop item with Trash 

### ISSUE THREAD

**Issue by sajumani** [marceljuenemann/angular-drag-and-drop-lists#204]
Hi

dnd-drop and dnd-inserted not working with dnd-list = []

i want to delete this in Database to but i failed to get the info of trashed item

reply ASAP

**Comment by marceljuenemann** [comment]
Works fine for me: https://jsfiddle.net/20zcmnw6/

**Comment by sajumani** [comment]
thanks for your reply,

now we can get the trash item, but its getting clone with original container...

**Comment by gerome0123** [comment]
@marceljuenemann hi how can i change the color in the dropzone?? once you something to drop???
