### ISSUE TITLE
get the drop item with Trash and unset the item in the list

### ISSUE THREAD

**Issue by sajumani** [marceljuenemann/angular-drag-and-drop-lists#206]
https://github.com/marceljuenemann/angular-drag-and-drop-lists/issues/204

dnd-drop and dnd-inserted not working with dnd-list = []
i want to delete this in Database too but i got the info of trashed item
but its getting clone with original container...

**Comment by marceljuenemann** [comment]
I can only guess without code, but you probably didn't return on object in the dnd-drop handler, so the drop operation was aborted.

**Comment by sajumani** [comment]
Yes, now its working fine.... Thanks alot
