### ISSUE TITLE
is it possible to get the drag effect to change a 'position' value (e.g. list.item.position) instead of the actual position the array and to return the position in the array where the item was dropped?

### ISSUE THREAD

**Issue by dashmaker** [marceljuenemann/angular-drag-and-drop-lists#209]

**Comment by marceljuenemann** [comment]
If you use dnd-drop and return true in the callback then the directive won't change your model at all. You can use the dnd-dragover or dnd-drop callback to update the position field, but I guess that will only work if you have a single list.
