### ISSUE TITLE
IE9 Double click deletes Item

### ISSUE THREAD

**Issue by Roadis** [marceljuenemann/angular-drag-and-drop-lists#21]
In all the demos when you double click with IE9 the Element will be deleted.
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested

The problem is that the dragstart event will be fired on a doubleclick. Then it starts to drag and just disappears. 

I looked at the code but couldnt find it yet. If i find it I will post it here

Greetings 
Jannis

**Comment by tommyboy123** [comment]
Seems to work as long as Documents Mode = Standard, regardless if IE version.  Any chance this will get fixed ?  Other than this double click issue, I'm very happy with this lib...

**Comment by idealeric** [comment]
This issue also manifests itself when you drag an item "outside" of a dropzone; the item never unhides itself because the .dndDraggingSource class is never removed.
