### ISSUE TITLE
splice is not a function in three level hierarchy

### ISSUE THREAD

**Issue by merlinschumacher** [marceljuenemann/angular-drag-and-drop-lists#217]
Hey,

i'm currently implementing a menu editor. I currently have the problem, that the first level of elements is perfectly draggable, the levels two and three only return errors about splice or eval not being a function. Dragging works, but the inserting fails. It's mostly a mix of the nested and the advanced demo.
Here is a codepen with my code: http://codepen.io/merlin-schumacher/pen/VaZWEe

**Comment by marceljuenemann** [comment]
If it can't find splice then it means the object you are calling splice on is not an array. There must be something wrong with your template.

**Comment by noherczeg** [comment]
This lib reliest on matrixes not lists, check if you have your 2 dimensional data structure! Most likely you are calling splice on an object not the second level list.
