### ISSUE TITLE
Disable dropzones adjacent to a element.

### ISSUE THREAD

**Issue by Soren234** [marceljuenemann/angular-drag-and-drop-lists#219]
Is it possible to disable dropzones next to a element in the list? 
Something like .dndPlaceholder li:first-child, to disable the dndPlaceHolder on the first element in the list?

**Comment by marceljuenemann** [comment]
You can have a custom dnd-dragover handler that has access to the index, and can then return false if that index is not allowed. See advanced demo for an example.
