### ISSUE TITLE
simple demo: where is $scope.list defined?

### ISSUE THREAD

**Issue by cleechtech** [marceljuenemann/angular-drag-and-drop-lists#222]
For the simple demo I do not understand where `$scope.list` is defined. The [demo](http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/simple) uses an ng-repeat on list and sends "list" to the dnd-list attribute but it is not defined in the controller! I am also thrown off because there is only one `ul` but two lists are displayed (corresponding to `$scope.models.lists.A` and `$scope.models.lists.B` .

I tried getting my own demo working. I copied the CSS. The lists display but the drag is not persistent. ie the drop is not working.

Controller:

```
app.controller('MainCtrl', function($scope){

    $scope.models = {
        selected: null,
        lists: {"A": [], "B": []}
    };

    // Generate initial model
    for (var i = 1; i <= 3; ++i) {
        $scope.models.lists.A.push({label: "Item A" + i});
        $scope.models.lists.B.push({label: "Item B" + i});
    }

    // Model to JSON for demo purpose
    $scope.$watch('models', function(model) {
        $scope.modelAsJson = angular.toJson(model, true);
    }, true);
});
```

HTML:

```
<div class='row'>
	<div class='col-sm-6'>
		<ul dnd-list="list">
		    <li ng-repeat="item in models.lists.A"
		        dnd-draggable="item"
		        dnd-moved="list.splice($index, 1)"
		        dnd-effect-allowed="move"
		        dnd-selected="models.selected = item"
		        ng-class="{'selected': models.selected === item}"
		        >
		        {{item.label}}
		    </li>
		</ul>
	</div>
	<div class='col-sm-6'>
		<ul dnd-list="list">
		    <li ng-repeat="item in models.lists.B"
		        dnd-draggable="item"
		        dnd-moved="list.splice($index, 1)"
		        dnd-effect-allowed="move"
		        dnd-selected="models.selected = item"
		        ng-class="{'selected': models.selected === item}"
		        >
		        {{item.label}}
		    </li>
		</ul>
	</div>
</div>
```

I would like to have two lists that I can drag and drop from and into each other like in the simple demo.

**Comment by cleechtech** [comment]
I still don't understand where `list` comes from but I got it working. Here is the markup to make the simple demo work:

```
<div class="row">
	<div ng-repeat="(listName, list) in models.lists" class="col-md-6">
		<ul dnd-list="list">
    		<li ng-repeat="item in list" 
    			dnd-draggable="item" 
    			dnd-moved="list.splice($index, 1)" 
    			dnd-effect-allowed="move" 
    			dnd-selected="models.selected = item" 
    			ng-class="{'selected': models.selected === item}" 
    			draggable="true">{{item.label}}</li>
		</ul>
	</div>
</div>
```

There needs to be two ng-repeats!

**Comment by meenakshijha** [comment]
@connor11528  Thanks for giving the markup.I was going crazy to make it work. The demo code clearly misses the ng-repeat part. 
BTW, the lists are generated using the below code in the controller.

 // Generate initial model
		    for (var i = 1; i <= 3; ++i) {
		        $scope.models.lists.A.push({label: "Item A" + i});
		        $scope.models.lists.B.push({label: "Item B" + i});
		    }
