### ISSUE TITLE
dndDrop handler : Uncaught ReferenceError: index is not defined

### ISSUE THREAD

**Issue by j040p3d20** [marceljuenemann/angular-drag-and-drop-lists#223]
Hi,

I'm using this dndDrop handler

```
				$scope.dndDropHandler = function(){
					console.log( "dndDropHandler");
					console.log( "event" , event );
					//console.log( "index" , index );
					//console.log( "item" , item );
					console.log( "external" , external );
					//console.log( "type" , type );
					return true;
				}
```

but I can't access most of the properties supposed to be available as local variables in the callback. I can only access "event" and " external".

The reason why I need this is because I'm using it in a table header and the first &lt;th&gt; is static, not bound to the item list, so I need to manipulate the insertion index because your algorithm assumes that the indexes of the html elements in the parent container match the indexes of the data elements in the list model.

BTW congratulations for the awesome work, this is really useful and yet simple to use and understand.

**Comment by iblamefish** [comment]
You are missing the parameters in the `dndDropHandler` callback function. The `event` and `external` variables are global (i.e. `window.event` and `window.external`.)

This is how to get access to them: 

    $scope.dndDropHandler = function(event, index, item, external, type) {
      // ...
    }

**Comment by marceljuenemann** [comment]
The variables are only available inside the dnd-drop attribute. If you call a function on your scope, you have to pass the variables that you want to use into the function as parameters.
