### ISSUE TITLE
Add dndDraggingSourceCopyMove to source element

### ISSUE THREAD

**Issue by raimund-schluessler** [marceljuenemann/angular-drag-and-drop-lists#225]
It would be nice to have a custom css class added to the source element similar to ```dndDraggingSource``` but dependent on whether the element is moved or copied. This way it would be possible to hide the source element when it is moved and show it when it is copied.

I currently achieve this behaviour by using ```dnd-dragstart="dragStart(event)"``` and ```dnd-dragend="dragEnd(event)"``` with these functions
```javascript
dragStart = function($event) {
	if ($event.dataTransfer.effectAllowed === 'copy' ||
	($event.dataTransfer.effectAllowed === 'copyMove' && $event.ctrlKey)) {
		$($event.target).addClass('copy');
	}				
};

dragEnd = function($event) {
	$($event.target).removeClass('copy');
};
```
but it would simplify things when the directive could already do this.

**Comment by marceljuenemann** [comment]
This is not possible because the drop effect is only determined when you drop the element and unknown during dragstart. Also, when the user presses/releases the Ctrl key the source element would have to change, which above all is probably not the best user experience.
