### ISSUE TITLE
Update position attribute after reordering

### ISSUE THREAD

**Issue by steverob** [marceljuenemann/angular-drag-and-drop-lists#227]
Great library! I am using it to allow my users to reorder a list of items. The ordering is maintained in an attribute in the objects called `position`.

Once someone reorders the list by dragging and dropping an item in the list, I need to update the position attributes of the items that were affected by this reorder.

And also fire updates to the backed whenever the order changes.. for multiple items that are affected.

ANy hints..?

**Comment by marceljuenemann** [comment]
Use $scope.$watchCollection
