### ISSUE TITLE
with Protractor, dnd-dragstart is not triggered.

### ISSUE THREAD

**Issue by digicom1978** [marceljuenemann/angular-drag-and-drop-lists#228]
Hi, I am trying to test the drag and drop list with protractor.

with native_js_drag_and_drop_helper.js, I could drag and drop element
but, its dnd-dragstart is not triggered.

Is there any way to trigger it?

Thanks in advance.

**Comment by orenhaliva** [comment]
I am also having trouble with this library and selenium.
Did you get any progress?
