### ISSUE TITLE
Moving an item from one list to another seems to lose the prototype class

### ISSUE THREAD

**Issue by Deklin** [marceljuenemann/angular-drag-and-drop-lists#232]
In my test, i have an object called ActionModel
When i move it from one array to another, it is being moved as an Object and loses its prototype chain.

Is there some setting i'm missing to avoid this? Or can I handle the move logic myself to make sure its not lost.

**Comment by dimw** [comment]
@Deklin, the prototype chain is also getting lost when moving or copying the object within the same list. This behavior seems to be described in the [Documentation](https://github.com/marceljuenemann/angular-drag-and-drop-lists#dnd-draggable-directive):

> dnd-draggable Required attribute. The value has to be an object that represents the data of the element. *In case of a drag and drop operation the object will be serialized and unserialized on the receiving end.*

However, I have solved the issue by defining a custom [drop callback](https://github.com/marceljuenemann/angular-drag-and-drop-lists#dnd-list-directive) on the list and passing the transferred object called ```item```:
```html
<ul dnd-drop="handleDrop(item)" ...>
    ...
</ul>
```
Then, the handler method converts the plain object back to the initial type and returns the new instance, e.g.:
```javascript
$scope.handleDrop = function (item) {
  var model = modelFactory(item);
  return model;
};
```
The module uses returned object for insertion into the array.

**Comment by marceljuenemann** [comment]
You can now also do this using the dnd-callback, see https://jsfiddle.net/Ldxffyod/1/

Small caveat is that this does not work with dnd-external-sources, but that shouldn't be a problem for most people.
