### ISSUE TITLE
Is it possible to get this working with directives?

### ISSUE THREAD

**Issue by garrickb** [marceljuenemann/angular-drag-and-drop-lists#233]
I have been trying for quite a while to get this functioning properly with directives instead of templates, but will it be impossible since the scope data isn't shared between a recursively created directive?

For some more detail, my directive uses an `ng-switch` to check whether or not the type of the object is a container or an item, and it will recursively navigate through all of the items in the array to display all nested items.

**Comment by zatziky** [comment]
@garrickb It's possible. I am using this library with components of AngularJS 1.5

**Comment by marceljuenemann** [comment]
Yeah, but you'll have to pass all the variables you need to the isolated scope
