### ISSUE TITLE
Not working with item-type in nested structure

### ISSUE THREAD

**Issue by patelchirag1987** [marceljuenemann/angular-drag-and-drop-lists#235]
Hi, 
I am creating the drop area with nested structure like this:
```
<ul>
   <li>
     <div>
         <ul>          <-------------- For rendering children
              <li></li>  
              <li></li>
         </ul>
     </div>
   </li>
</ul>
```

Now I want the drag and drop functionality as below:

- I should not be able to drop element in between children **li**

The best example for this is to restrict dropping of item or container in nested example given.

**Comment by marceljuenemann** [comment]
You can use dnd-dragover to see the index and return false to disallow dropping
