### ISSUE TITLE
How to remove added item using button click

### ISSUE THREAD

**Issue by sajithpc** [marceljuenemann/angular-drag-and-drop-lists#239]
Created a item with button inside. This item can be dragged into dropzone and can be dragged to trashcan as well. Is it possible to replicate the same removal functionality with click of button inside the item. How to remove the entire item on click of the button.

**Comment by Neonchen** [comment]
Thats pretty easy. You can do something like:
<button type="button" ng-click="list.items.splice($index,1)"></button>

**Comment by sajithpc** [comment]
Thanks for Neonchen for hint.

**Comment by essivision** [comment]
`<button type="button" ng-click="list.splice($index,1)">X</button>`
