### ISSUE TITLE
Drag a simple object to create a more complex object 

### ISSUE THREAD

**Issue by safhac** [marceljuenemann/angular-drag-and-drop-lists#240]
Hi 
I have a `dnd-list` of `users` with many fields and arrays 
I need to drop into it a `dnd-draggable` of a `applicant` with only `name` and `email` so they can fill all the details.
right now dragging an `applicant` into the `users` list creates like a shallow copy of a user and the  `applicant` data isn't seen.
In `dnd-drop` i can drill down the `event.currentTarget` and set the fields there but it seems hacky 

is there a better way to implement something like this?

**Comment by safhac** [comment]
Hi 
If anyone's interested this can be achieved very simply by modifying the html template of `dnd-list` to accommodate different model structures.

**Comment by nicolasreich** [comment]
@safhac hi, I'm running into the exact same problem and I'm not sure I understand what you mean. How did you solve this? Thanks!
