### ISSUE TITLE
Try to add columns to the container

### ISSUE THREAD

**Issue by agomezru** [marceljuenemann/angular-drag-and-drop-lists#248]
I'm using the angularjs directive http://marceljuenemann.github.io/angular-drag-and-drop-lists/ to drag & drop things over the page.

I don't know if this is the best for what I need.

I've reproduce the demo

http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested

in a fiddle

http://jsfiddle.net/5yogbajq/16/

What I need is to add more columns on the container. I've added the 13th item and it goes to bottom and right. What I need is this one goes in the same row as Item 9 and Item 12, on the right. Something like:

<tr>
<td>item 9</td>
<td>item 12</td>
<td>item 13</td>
</tr>
Any help will be appreciatte.

Thanks in advance.

**Comment by jmls** [comment]
did you solve the problem then ? If so, would you share the solution ? Thanks!

**Comment by agomezru** [comment]
@jmls

http://stackoverflow.com/questions/36745047/angularjs-directive-to-drag-drop-need-to-add-columns/36747507#3674750

your welcome

2016-05-04 10:48 GMT+02:00 jmls <notifications@github.com>:
