### ISSUE TITLE
Handling the cursor style during dragging

### ISSUE THREAD

**Issue by vardan-arm** [marceljuenemann/angular-drag-and-drop-lists#249]
Hi,

I would like to have "grabbing" cursor when dragging an item. I'm adding cursor cross-browser styles into "dndDragging" (and "dndDraggingSource", just for being sure that I'm not missing anything), but it doesn't affect to cursor style at all (it seems that I can't change the "default" cursor to any other one).

Is there any way to handle the cursor style during dragging event?

Thanks in advance!

**Comment by vardan-arm** [comment]
Any updates on this? We can't set any custom cursor style when an element is dragging. It seems that it always is overridden, which is not good at all.

**Comment by marceljuenemann** [comment]
Unfortunately, there's no way to set a custom cursor with HTML5 drag & drop, the cursor is determined by the browser. You can only do that when using a pure JavaScript drag & drop solution.
