### ISSUE TITLE
drag with click on mobile

### ISSUE THREAD

**Issue by NirAviel** [marceljuenemann/angular-drag-and-drop-lists#251]
Hi,
I have a drag list that in each item there is a button.
In mobile I can't get the button clicked, the drag start before the click and block it.

tnx

**Comment by mattheworres** [comment]
@NirAviel have you tried the IOS Drag Drop shim that is mentioned in the README?

**Comment by marceljuenemann** [comment]
You would have to file this with the iOS Drag Drop shim. It will be very hard to support tap + dragging at the same time, how would you distinguish those two user actions?
