### ISSUE TITLE
On dnd-effect-allowed="copy" item diappears from the original container.

### ISSUE THREAD

**Issue by MarkoIvanetic** [marceljuenemann/angular-drag-and-drop-lists#255]
It is intuitive that item disappears on "move" action but if I try to copy it to another container it might be better if item stays in original at all time instead of disappearing and reappearing again.

**Comment by jorism5** [comment]
Hi,
You can easily fix this behaviour removing this css class :
`.your-class ul[dnd-list] .dndDraggingSource {
  display: none;
}`
