### ISSUE TITLE
drag & drop should delete first and insert next?

### ISSUE THREAD

**Issue by pmjhonwang** [marceljuenemann/angular-drag-and-drop-lists#257]
my test was first insert and delete.

version 1.4.0

**Comment by pmjhonwang** [comment]
![image](https://cloud.githubusercontent.com/assets/1998455/14897558/10e0f0f0-0db5-11e6-968d-c47e9394c514.png)
![image](https://cloud.githubusercontent.com/assets/1998455/14897567/1af08088-0db5-11e6-8568-5ee2db091373.png)

**Comment by pmjhonwang** [comment]
no insert event trigger
![image](https://cloud.githubusercontent.com/assets/1998455/14897584/30054198-0db5-11e6-9ea8-17b21376c341.png)

**Comment by pmjhonwang** [comment]
sos pls

**Comment by AlekseySorokin** [comment]
I`ve the same problem. 
Bug due to additional element in the top of the list. Library somehow thinks that it is a draggable item. So the index is offset by 1.
