### ISSUE TITLE
Move Multiselect Lists with dnd-external-sources

### ISSUE THREAD

**Issue by brunomptorres** [marceljuenemann/angular-drag-and-drop-lists#258]
I've tried to pull a multiselect list using the dnd-external-sources, but the result is that only the last selected item (right before the drag) is moved to the other list.

I don't know if this functionality is already implemented or not. If so can you share how it's done properly?

Thanks in advance

**Comment by marceljuenemann** [comment]
Can't think of any reason why this shouldn't work. Can you create a jsfiddle?
