### ISSUE TITLE
Elements are duplicated if $$hashKey is removed

### ISSUE THREAD

**Issue by artoale** [marceljuenemann/angular-drag-and-drop-lists#260]
Assume the items in the list are `Resource`s (from ng-resource), and that you have an "order" property on each object which is kept up to date with the relevant in-list position (each time an item is moved, let's assume we call `item.$update()`). 

To keep the `MyClass = $resource(...)`  methods available on to the model we have to wrap the deserialized object in a MyClass call (inside `dnd-drop`) e.g.

```
$scope.onDrop = function (item) {
 return new MyClass(item);
}
```

This is somehow breaking this (btw, great!) library, since every time an instance function updates the model, it first cancel all its properties (including `$$hashKey`) and it then copy the resource returned from the network onto the old (now empty) object. 

now, I managed to workaround this issue by storing the `$$hashKey` before save, and updating it back 

```
var oldHashKey = this.$$hashKey;
return item.$save().then(function() {
                item.$$hashKey = oldHashKey;
});
```

which is of course a non reliable solution. 
Now, another possible approach would be to simply use `track by` with the item id (let's assume we have one unique identifier). That, unfortunately, will not work, since apparently the order in which insert/delete happen makes the "unique" id duplicated, thus resulting in an angular error.

I haven't digged into angular dnd's code, but it really feels like a bug somewhere - any idea?

**Comment by Jacke** [comment]
Any solutions?

**Comment by vsax** [comment]
I am struggling with this as well.

**Comment by noherczeg** [comment]
I can confirm this as well.

**Comment by cpgruber** [comment]
@artoale I essentially needed to do the exact same thing and found that [ng-sortable](https://github.com/a5hik/ng-sortable) plays best with angular resources (compared to angular-drag-and-drop-lists and ui-sortable). I tried for days to get this directive to work, while it took about an hour to get the desired behavior from ng-sortable.

**Comment by marceljuenemann** [comment]
I've got some ideas to add better support for this in the future. For now, a workaround would be to track-by the unique ID, and then have dnd-drop callback that removes the unique ID from the source element that will be removed (only has to be done if it's in the same list)

**Comment by vsax** [comment]
Thanks. It would help tremendously. I know more and more people are using the library now.

**Comment by marceljuenemann** [comment]
You can now also do this using the dnd-callback, see https://jsfiddle.net/Ldxffyod/1/

Small caveat is that this does not work with dnd-external-sources, but that shouldn't be a problem for most people.
