### ISSUE TITLE
dnd-disable-if, how to move items in the same line even if disabled ?

### ISSUE THREAD

**Issue by maxime1992** [marceljuenemann/angular-drag-and-drop-lists#261]
Hi,

I'd like to disable the drag n drop on a row if the row as 4 columns or more.

So basically, this would end up in something like this :

`dnd-disable-if="items.cols.length > config.maxCols"`

But now, I'm facing a problem : I cannot drag n drop in the same row if the row as 4 columns.

How can I tell the library :  "I want to disable the DND IF the maximum length for a column has been reached AND if I'm not moving the item into the same line" ?

Thanks for any help

**Comment by marceljuenemann** [comment]
You can use a dnd-dragover handler and return false to disallow the drop if your constraint is reached. See the advanced demo for an example of this.
