### ISSUE TITLE
How can i exchange the positions of two draggable items

### ISSUE THREAD

**Issue by huguangju** [marceljuenemann/angular-drag-and-drop-lists#263]
I just want to exchange positions of the two items, without disturbing other items position.

I tried to use `dnd-drop` or `dnd-inserted` event to get the index of target item position, but can't.

If move the item from front to back, the `dndPlaceholder` will insert after if target item and the index is `target item index + 1` , it's wrong result, but move item from back to front, the `dndPlaceholder` will insert before target item, so the result is ok.

I tried to use `dnd-dragover` event to get right index, but the `dndPlaceholder` li element disappeared and can't exchange the position of each item to other.

Thank you for your help. Forgive my poor English 😂

**Comment by marceljuenemann** [comment]
You can now do this using a custom dnd-callback, see https://jsfiddle.net/Ldxffyod/1/ for an example. Basically just replace the onDrop handler with a swap instead of a move algorithm.

**Comment by dexterBEN** [comment]
Good Morning,

This is an interesting feature, can i use it with angular 4 and yarn 1.5.1?

Thanks for answer ?
