### ISSUE TITLE
Does it work with array of strings instead of objects?

### ISSUE THREAD

**Issue by raviada** [marceljuenemann/angular-drag-and-drop-lists#264]
I am getting the following error when trying to drag and drop array B to reorder.

My arrays are like this.
A = ["One", "Two"]
B= ["Three", "Four", "Five"]

```
Error: ngRepeat:dupes Duplicate Key in Repeater
Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: item in list, Duplicate key: string:Five, Duplicate value: Five
```

Any ideas?

**Comment by onyoo** [comment]
@raviada you can use ng-repeat="<item> in <collection> track by $index"

**Comment by kheinrich188** [comment]
@onyoo this will not fix the Problem. See #114. When you use `track by index` you're error will remove but `dndlist` will then not working correctly when you move one lower item to a higher position. It seems to be duplicated here.

**Comment by marcelogo** [comment]
+1

**Comment by thisispaul** [comment]
+1

**Comment by LeviBarker** [comment]
+1

**Comment by smonkey72** [comment]
You can use `dnd-drop` to handle the reorder by yourself with a few lines of code like:

```javascript
function drop(list, item, newIndex) {
  	var oldIndex = list.indexOf(item);
    // handle same-list (reorder)
  	if (oldIndex !== -1) {
      if (newIndex > oldIndex) --newIndex;
      list.splice(oldIndex, 1);
      list.splice(newIndex, 0, item);
      return false; // cancel drop (dnd-moved will not executed)
    }
    // otherwise, proceed by default
    return item;
  }
```

[Here is a working Fiddle.](https://jsfiddle.net/vpq9ta4v/)

Remember: due to the nature of string arrays, this is only working with `move` and unique strings.

**Comment by JanEggers** [comment]
+1 @smonkey72 works like a charm
should be merged as default behavior

**Comment by kheinrich188** [comment]
+1 @smonkey72

**Comment by marceljuenemann** [comment]
The problem was that there were duplicate strings in the ng-repeat for a brief moment (between inserting the new one and removing the old one). You can now perform the move immediately by using the dnd-callback.

I put together a fiddle here: https://jsfiddle.net/t429fe50/
