### ISSUE TITLE
cancel drag op?

### ISSUE THREAD

**Issue by nihlton** [marceljuenemann/angular-drag-and-drop-lists#265]
I've got a list of items which also have a long-press action.

how can i cancel the drag event currently in progress once long press has fired?

currently trying:

```
< element
dnd-dragstart="dragEvents.push(event); "   
dnd-dragend="dragEvents = [];"
on-long-press="myFunc()" />
```

while myFunc contains:

```
for( var x in $scope.dragEvents ){ 
	$scope.dragEvents[x].preventDefault();
	$scope.dragEvents[x].stopImmediatePropagation();
}
```

but this doesn't seem to work....

**Comment by nihlton** [comment]
ok, i got something worked out.  i modified the IOs shim to fire long press events, and cancel drag and drop if it fires.  And vice versa - to cancel the long press if user begins dragging after picking up the element.

its kind of a hack, but it works.

**Comment by lumalav** [comment]
Haven't you tried using the directive dnd-disable-if?

**Comment by marceljuenemann** [comment]
I don't think it is possible with the HTML5 API to cancel drags after they started. The iOS shim could certainly implement something like that though, please file that issue with them though.
