### ISSUE TITLE
locate its original placement

### ISSUE THREAD

**Issue by jrran90** [marceljuenemann/angular-drag-and-drop-lists#271]
Good day, bare with me, though, I'm still new with angularjs and I'm quite confused with the docs.
Anyways, my problem is, let say for example, I have 2 lists namely, "list A" and "list B". I transferred one of the entries from list A to B. How would I know that the entry that I transferred to B comes from A or etc?? sort of tracing up its original placement prior it was transferred to another set of list.

Thanks

**Comment by marceljuenemann** [comment]
This is now possible with a custom dnd-callback
