### ISSUE TITLE
Can we help for creating  "Nested Containers" with item and containers restrictions

### ISSUE THREAD

**Issue by itsmartyexpert** [marceljuenemann/angular-drag-and-drop-lists#279]
Hello Sir,

I would like to develop a drag and drop similar "Nested containers" but in this also want to add restrictions for example  allow items in containers only out side "containers" don't allowed to drag and drop the items.
And also don't want to drag "containers" inside "containers".

Can you please help me or give some hint how to achieve this.

Thanks in advanced.
Jack R

**Comment by SarahD** [comment]
Hi Jack - Did you figure this one out? I am in the same need.

**Comment by marceljuenemann** [comment]
dnd-type and dnd-allowed-types are your friends, check out http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced

**Comment by itsmartyexpert** [comment]
Hi @SarahD , Did you figure out above one? Can you please provide if yes.
