### ISSUE TITLE
Empty lists

### ISSUE THREAD

**Issue by Mezajakko** [marceljuenemann/angular-drag-and-drop-lists#282]
I drop all items from list A to list B. so, when I want drop all items to list A again, I cant. While the lists are empty I can't do it.

**Comment by wagedomain** [comment]
What's the behavior? You may want to give the list a min-height, otherwise there's nowhere to drop the item onto.

**Comment by marceljuenemann** [comment]
Correct, you can't drop to a list that has a height of zero, since you won't ever be able to hover over it.
