### ISSUE TITLE
Code is not working

### ISSUE THREAD

**Issue by kinghemantraj** [marceljuenemann/angular-drag-and-drop-lists#283]
Hi,
Below is source code url which is not working.
https://plnkr.co/edit/nfPSuU8293U809a4aIA2?p=preview
Could you please tell me what is error?

**Comment by meenakshijha** [comment]
The html code is incomplete. Follow this link and copy the entire markup code.

https://github.com/marceljuenemann/angular-drag-and-drop-lists/tree/master/demo
