### ISSUE TITLE
How to I keep my list items from being transparent on dragging? 

### ISSUE THREAD

**Issue by impavidum** [marceljuenemann/angular-drag-and-drop-lists#284]
I can apply styles to elements within the li by using .dndDragging class, but no matter what I do it still adds opacity of 70% or so to the element being dragged which is annoying if this is not the effect you are going for..

**Comment by marceljuenemann** [comment]
The opacity effect is applied by the browser automatically, there's nothing we can do. Note you can set a custom drag image (see multiselection demo), but it will still be transparent.
