### ISSUE TITLE
Digest Cycle for angular goes in infinite loop

### ISSUE THREAD

**Issue by dubey-aditya** [marceljuenemann/angular-drag-and-drop-lists#285]
As number of item increase in list it will throw error of digest cycle goes in infinite loop. It render the whole  list but a huge error on console is shown.

**Comment by marceljuenemann** [comment]
Do you have a demo (jsfiddle) for that? Are you calling $digest in one of your custom callbacks?

**Comment by dubey-aditya** [comment]
I have used it in a drag drop tool for building UI. Which consists of parent child relationship but the thing  is that when hierarchy grows it breaks.

Like I tried to build a nested DOM structure with this list items created a json and stored but when I try to render the same json again I get the error of digest cycle going infinite on console. Angukar handle's it and render the hierarchy of items.

As I understand ng- repeat won't be abke to accumulate the large list iteration in one go.

Hope U will get the problem. As I am not working on the same project and Company so cant share my problem with fiddle.


But surly I will share the problem If I get time, till then you can close it.

Aditya Dubey
ES5_Developer
3DPLM Software
