### ISSUE TITLE
How to get property of item and where to where it is moved ?

### ISSUE THREAD

**Issue by gautamgolakiya** [marceljuenemann/angular-drag-and-drop-lists#286]
I am using this as drag and drop functionality but i have one question about drag and drop. When i drop the any item to anywhere in the same container or any other container then how i am get the position of that item and where to where it is moved ?

**Comment by kebre001** [comment]
If you look at the following example from the demo page you can get the event and from there you can get the parent element with:

`event.target.parentNode.id`

With help from the callback you can get index, item and event.
DEMO
`<ul dnd-list="items"
                dnd-allowed-types="['itemType']"
                dnd-horizontal-list="true"
                dnd-external-sources="true"
                dnd-dragover="dragoverCallback(event, index, external, type)"
                dnd-drop="dropCallback(event, index, item, external, type, 'itemType')"
                dnd-inserted="logEvent('Element was inserted at position ' + index, event)"
                class="itemlist">
                <li ng-repeat="item in items"
                    dnd-draggable="item"
                    dnd-type="'itemType'"
                    dnd-effect-allowed="copyMove"
                    dnd-dragstart="logEvent('Started to drag an item', event)"
                    dnd-moved="items.splice($index, 1); logEvent('Item moved', event)"
                    dnd-copied="logEvent('Item copied', event)"
                    dnd-canceled="logEvent('Drag operation canceled', event)"
                    dnd-dragend="logEvent('Drag operation ended', event)">
                    {{item.label}}
                </li>
            </ul>`
