### ISSUE TITLE
need to add UI controllers using drag and drop

### ISSUE THREAD

**Issue by Aman91Goyal** [marceljuenemann/angular-drag-and-drop-lists#288]
i need to convert this demo in form builder http://kelp404.github.io/angular-form-builder/  like we have in this demo.

But in this demo we don't have feature of container. so please suggest me how i can convert this demo to form builder with container and item form.

In your demo i am not able to add more UI controller instead of list only.

**Comment by marceljuenemann** [comment]
That's a very broad question, I'll probably not gonna be able to help you with that. You'll need to understand how the directive works from studying the demos, and then think about how to apply it to what you want to do...
