### ISSUE TITLE
Question: adding an item can sometimes cause some jumpiness

### ISSUE THREAD

**Issue by paulflo150** [marceljuenemann/angular-drag-and-drop-lists#29]
Hi,
thanks for this great plugin! 

In the nested list example, I am having a little trouble dropping items into a container that has several items on the left column for instance, and none on the right - the drop placeholder starts alternating between the correct place for the item I am trying to drop, and the drop zone above the container making it very hard to drop it. Any thoughts on how to fix this? 

Here are steps to reproduce the problem (I am using latest Chrome) - in Dropzone A, start dragging Item 3 out of its place and then try to drop it back in the sample spot.

Thanks

**Comment by marceljuenemann** [comment]
I see what you mean. The only solution is to increase the min-height of the dropzone, so that when the placeholder above it is removed, the mouse cursor is still inside the dropzone.
