### ISSUE TITLE
Add support for creating drop zones

### ISSUE THREAD

**Issue by josueespinosa** [marceljuenemann/angular-drag-and-drop-lists#290]
In my current use case, I have a container filled with several lists.

It would be useful to me if when you drag a list element out of a parent list and you don't drag it into another list, e.g. in-between 2 lists, there is a placeholder list, where if you drop it there, it creates a new list with the list element that was dropped onto it.

Sorry if that is difficult to understand, I found it challenging to describe the behavior in a clear way.

Would it be possible to add this functionality for future releases?

**Comment by marceljuenemann** [comment]
Well, that's certainly already possible. Instead of the dropzone just use a dnd-list with a custom dnd-drop handler. You don't actually need to store it in a list, if you return true in the dnd-drop handler you can handle the drop any way you want.
