### ISSUE TITLE
DnD placeholder flashes when dragging table rows in Chrome

### ISSUE THREAD

**Issue by plaa** [marceljuenemann/angular-drag-and-drop-lists#291]
I'm trying to use the module to add drag-and-drop support to rows of an HTML table.

The problem I'm seeing is that whenever the DnD placeholder takes up vertical space, it sometimes starts flashing on and off while dragging in Chrome / Chromium.

Steps to reproduce:
 1. Open the example JSFiddle in Chrome:  http://jsfiddle.net/0yua4f15/2/
 2. Slowly drag e.g. "five" to a higher position, and keep the mouse button pressed
 3. Once you hit a magic position, even though you don't move the mouse, the placeholder flashes on and off at about 0.5s interval.  (This seems to occur when the mouse is in a position where it would hover over the placeholder when it is present, though not necessarily always.)  Dropping works only if you release the mouse button while the placeholder is present.

There are two variants in the JSFiddle which can be enabled by removing the comment marks, neither of which fix the issue:
 - Style the generated `<li>` element as a table row by CSS
 - Define a custom `<tr>` element as the placeholder in HTML

Tested to be buggy on Chrome 49 and Chromium 49 running on Linux Mint.  On Firefox 46 it works correctly as long as one of the options is uncommented.

**Comment by plaa** [comment]
After re-testing, it works in Chrome after all, as long as:

 1. There is a custom `<tr class="dndPlaceholder">` implemented; and
 2. The placeholder row contains the same amount of `<td>`s (or equivalent using `colspan`) as the rest of the table.

I'm not sure how I missed this.  Hopefully this will help out other people struggling with the same issue.

**Comment by RobbertWolfs** [comment]
Did you place the custom tr element inside the dnd-list or outside of it ?

**Comment by AbiSadhasivam** [comment]
Hi, 

Is there an implementation available for dndPlaceholder for tr ?

**Comment by hendricius** [comment]
Also curious - how did you get this to work?

**Comment by rushdykamel** [comment]
What @plaa did is adding `<tr class="dndPlaceholder"><td colspan="2"></td></tr>` inside the `<tbody>` tag, as following:
```
<tbody dnd-list="numbers" dnd-drop="dropped(event, index, item, external, type)">
      <tr ng-repeat="number in numbers" dnd-draggable="number">
        <td>{{$index}}</td>
        <td>{{number}}</td>
      </tr>
     <!-- OPTIONAL - define a custom <tr> placeholder -->
     <tr class="dndPlaceholder"><td colspan="2"></td></tr>
</tbody>```
