### ISSUE TITLE
Moving remove incorrect item from source list when applying filter on source list

### ISSUE THREAD

**Issue by CHOMNANP** [marceljuenemann/angular-drag-and-drop-lists#294]
I have two lists. 1 is source and another one is dest list. I have apply filter in source, the I have some problem with moving the object after filter.

For example, this is the 
source = "X":[{"label":"Item A1"},{"label":"Item A2"},{"label":"Item B1"}]
Dest = "Y" : [];

If I filter B, the source(X) only display "Item B1". ( Selected index = 0, item index = 2 )
Then if I drag "Item B1" into dest(Y), the source(X) only remain "X":[{"label":"Item A2"},{"label":"Item B1"}]

It doesn't remove item by item index(2) , but it remove source by selected index(0).

I have changing dnd-moved="list.splice(list.indexOf($index), 1)", but it doesn't work.

Anyone have the same issue?

**Comment by Ilair** [comment]
Olá! Estou tendo um problema semelhante, alguém possui uma solução para isso? 
Grato pela atenção!

**Comment by Mezajakko** [comment]
How can I add a filter to lists ?

**Comment by CHOMNANP** [comment]
Hi,

You can refer to this code.


<input class="pull-right" ng-model="search.label" />

<ul dnd-list="list">
    <li ng-repeat="item in list | filter:search:strict"
        dnd-draggable="item"
        dnd-moved="list.splice($index, 1)"
        dnd-effect-allowed="move"
        dnd-selected="models.selected = item"
        ng-class="{'selected': models.selected === item}"
        >
        {{item.label}}
    </li>
</ul>


For your reference: https://docs.angularjs.org/api/ng/filter/filter

Thanks,
Punleu

**Comment by Mezajakko** [comment]
Thanks,

I could do it, but I' having a strange behavior. When I search the item what is in the first position of the list, the element is dropped correctly and removed from list A to list B, but when I search other element that isn't the first in the list, when I'm trying to drop it to list B I can do it but the item doesn't removed from list A.

Excuse me for the possibles grammatical errors, I hope you understood me

**Comment by CHOMNANP** [comment]
I think we're having the same issue.
I'm trying to get someone who experience with this issue as well.
Thanks,
Punleu

**Comment by Mezajakko** [comment]
This issue is caused by this type of filter "| filter:searchFilter" 

I used ng-show into <li></li> and the condition only shows the filter results but not changes the index of the results, you need to create a controller method using Javascript's method includes()

`<div class="panel-body">
                                                                <input type="text" 
                                                                       class="form-control" 
                                                                       ng-keydown="reCuestionario.onFiltrar(item.enunciado)" 
                                                                       ng-model="reCuestionario.descripcionPregunta"
                                                                       style="margin-bottom: 10px;
                                                                       border-color: black;"
                                                                       placeHolder="Buscar Pregunta..." st>
                                                                <ul style="overflow-y: scroll; max-height:300px;min-height: 300px;" dnd-list="reCuestionario.listaPreguntas">
                                                                    <li ng-repeat="item in reCuestionario.listaPreguntas"
                                                                        class="ng-binding ng-scope"
                                                                        ng-show="reCuestionario.onFiltrar(item.enunciado)"
                                                                        dnd-draggable="item"
                                                                        dnd-moved="reCuestionario.listaPreguntas.splice($index, 1)"
                                                                        dnd-effect-allowed="move"
                                                                        dnd-selected="models.selected = item"
                                                                        ng-class="{'selected': models.selected === item}" class="simpleDemo">
                                                                        {{item.enunciado}}
                                                                    <li class="dndPlaceholder">
                                                                        Soltar aquí
                                                                    </li>
                                                                </ul>
                                                            </div>`

**Comment by marceljuenemann** [comment]
The directive doesn't remove any items, it just invokes dnd-moved. If you use a filter then inserting at the right position and removing the correct elements is up to you. You should probably remove by some custom id field rather than by index. An easier approach might be too not use filter: and instead create a separate filtered array that you keep in sync with $watches.

**Comment by MikaelLambert** [comment]
I independently came up with the same possible solution as @Mezajakko. You can use ng-show instead of filter on ng-repeat. This might not work in all cases but worked for me.

Before:
`<li ng-repeat="item in list  | filter : {hideItem: true}">`

After:
`<li ng-repeat="item in list" ng-show="item.hideItem">`
