### ISSUE TITLE
dnd-moved does not fire when a breakpoint is set in dnd-drop

### ISSUE THREAD

**Issue by MPeeples** [marceljuenemann/angular-drag-and-drop-lists#297]
I'll place my code here, and I've confirmed that this bug is observable in the demo website, as well. I am using Chrome, `Version 51.0.2704.106 unknown (64-bit)`.

If you are using a dnd-drop callback function to splice an object into a list, and using the dnd-moved callback to splice the object you were moving out of the original list (e.g., moving an object to a different index), and you set a breakpoint inside the dnd-drop callback, the dnd-moved callback doesn't fire.

For example, here is my code:

```
function addToAssessment(event, index, items, list) {
    /**
     * In the dnd-drop callback, we now have to handle the data array.
     * We handle the insertion into the list ourselves. By returning
     * true, the dnd-list directive won't do the insertion itself.
     */
     angular.forEach(items, function(item) {
         item.selected = false;
         // When a new standard is dropped in from the search box, create a wrapper object around the standard
         if (item.type == 'standard' && !item.standard) {
             //trim the standard data
             item = {
                 'guid': item.guid,
                 'type': item.type,
                 'standard': trimStandard(item)
             };
         } else if (item.type == 'genre' && typeof item.genre != 'object') {
             item = {
                 'type': item.type,
                 'genre': trimGenre(item)
             }
         }

         // If this is a newly added element, generate and set an ID
         if (!item.id) {
             sasService.getElementID(item.type).then(function(id) {
                 item.id = id;
                 list.splice(index, 0, item);
             });
         } else {
             list.splice(index, 0, item);
         }
     });
     vm.enableSave();
     return true;
}

function moveList(list, index) {
    console.log("Remove object at index " + index + ": " +list[index]);
    list.splice(index, 1);
}
```

And the HTML:
```
<ul>
    <li ng-repeat="(assessmentkey, list) in detail.models.assessments"
        ng-if="list.type === 'interim'">
        <div class="assessment box" assessment="list">
            <an-assessment-header assessment="list"
                                  delete-assessment="detail.deleteAssessment(assessmentkey)"
                                  subject="{{detail.blueprint.subject}}"
                                  enable-save="detail.enableSave()">
            </an-assessment-header>
            <!-- The dropzone also uses the list template -->
            <ul dnd-list="list.children"
                dnd-drop="detail.addToAssessment(event, index, item, list.children)"
                ng-class="{empty: list.children.length === 0}">
                <li ng-repeat="item in list.children"
                    dnd-draggable="[item]"
                    dnd-effect-allowed="move"
                    dnd-dragstart="detail.showDeleteZone()"
                    dnd-dragend="detail.hideDeleteZone()"
                    dnd-moved="detail.moveList(list.children, $index)"
                    dnd-selected="models.selected = item"
                    dnd-disable-if="detail.disableDrag"
                    class="draggable"
                    ng-class="{selected: models.selected === item}"
                    ng-if="item.type !== 'note'"
                    ng-include="'selected' + item.type + '.html'">
                </li>
            </ul>
            <button type="button" class="btn add-unit pull-right"
                    ng-click="detail.addUnit(assessmentkey)"
                    ng-show="detail.blueprint.subject === 'ela'"
                    tooltip="Add unit">
                <span class="glyphicon glyphicon-plus"></span>
            </button>
        </div>
    </li>
</ul>
```

If I set a breakpoint inside the `addToAssessment()` function, anywhere, after hitting it, the console.log in `moveList()` never fires. As soon as I remove the breakpoint, it does fire, and works smoothly.

You can also see it in http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced.

If you open up the dev console, set a breakpoint on `angular-drag-and-drop-lists/demo/advanced/advanced.js`, line 10, `$scope.logListEvent('dropped at', event, index, external, type);`, and then try to drop item 36 from one container to another, you will see that the `dnd-moved` callback, `dnd-moved="items.splice($index, 1); logEvent('Item moved', event)"`, never gets called, and you are left with a duplicate item. If you remove the breakpoint, watch the console, and you will see that "Item copied" does get logged properly, and the item is spliced from the list.

Not sure what can be done about this, but it'd make debugging a lot easier if fixed.

**Comment by Joe-Withey** [comment]
This is because adding a breakpoint to a script will halt the entire script execution. Not a specific function call. It is impossible to do what you are asking. You will have to use an alternative method of debugging using what you know about the two method calls; dnd-moved is invoked after dnd-drop.

**Comment by marceljuenemann** [comment]
Sounds like a bug in Chrome to me? Don't think there's anything at all we can do on our side.

**Comment by jerwen** [comment]
I've been doing some debugging on the 'advanced' demo provided and I found out that when you add a breakpoint into the drop's event handler in `angular-drag-and-drop-lists/angular-drag-and-drop-lists.js`, the dndCancelled callback is fired (is it suppose to happen ?) which, I guess, prevents the dnd-moved callback to be fired

`advanced.js:19 itemType element is dragged over position 6 (triggered by the following dragover event)

advanced.js:19 Drag operation canceled (triggered by the following dragend event)

advanced.js:19 Drag operation ended (triggered by the following dragend event)`

And when you proceed with the previously broke drop's event handler, you obtain this :

`advanced.js:19 External undefined element is dropped at position 6 (triggered by the following drop event)

advanced.js:19 Element was inserted at position 6 (triggered by the following drop event)`


It also made me realize that the 'external' property provided into the `invokeCallback` function, doesn't really provide the information required (which is to tell if the element being dropped comes from an external source).
