### ISSUE TITLE
Nested object inside dragged objects are lost after drop

### ISSUE THREAD

**Issue by noherczeg** [marceljuenemann/angular-drag-and-drop-lists#302]
Let's say we have a list of objects like this:

```
{
  id: X,
  name: Y,
  nested: {
    foo: 1,
    bar: 0
  }
}
```

If I drag objects like this then after I drop them the `nested` attribute which is an object is lost in the process. So I get something like this:

```
{
  id: X,
  name: Y
}
```

**Comment by marceljuenemann** [comment]
Do you have a jsfiddle for that? If they are normal objects as you say, this should work, as you can also see in the nested demo. It doesn't currently work with prototypes/class objects, since they will be serialized.
