### ISSUE TITLE
Component Ember

### ISSUE THREAD

**Issue by aureliosaraiva** [marceljuenemann/angular-drag-and-drop-lists#303]
Hello, how are you?

First I would parabelizar by the component it has been very useful to me.

But I'm using it in Ember.js for that I migrated rules using Ember components.

At the moment it is a private project, but would like to build a Ember.js component and available to the community using the same license distribution.

I can provide to the community?

**Comment by marceljuenemann** [comment]
Sure, it's MIT licensed, you don't need my permission for that.

Marcel
