### ISSUE TITLE
Getting start with module is bad

### ISSUE THREAD

**Issue by essivision** [marceljuenemann/angular-drag-and-drop-lists#304]
Hi
I want to getting start with your module but not successful while found out you set some variable to simple-frame. I think users confuse about it and I recommend to review your demo and create a simple getting start to your module in documentation.

Thanks

**Comment by marceljuenemann** [comment]
Sounds like you looked at the source code of the demo rather than the demo itself. If you follow the links in the readme you come to http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/simple, which shows all the code you need (which is not very much)
