### ISSUE TITLE
Probably a newb question - D&D copy, but have an in-row delete option only on copy

### ISSUE THREAD

**Issue by SarahD** [marceljuenemann/angular-drag-and-drop-lists#309]
Hi there!
Rocking tool btw. Loving what it can do!

I am using your D&D to copy items from one container (strictly) to a list and containers cannot be moved to the other list or inside each other. I need to have it so that the copied item can specifically be deleted, but the original cannot. Unfortunately, I am rather new to this, so I am likely just overlooking something in the documentation. Any help would be appreciated.

Here's my fiddle: https://jsfiddle.net/webdevsarah/6unyopuk/

Thank you so much!

**Comment by marceljuenemann** [comment]
It's probably the easiest to have separate code for the different lists you have, rather than using the list.html template. That way it's either to implement the different behavior, e.g. your project containers don't need to be dnd-draggable at all.
