### ISSUE TITLE
Uncaught TypeError when invoking dnd-drop callback

### ISSUE THREAD

**Issue by madriman** [marceljuenemann/angular-drag-and-drop-lists#311]
I have implemented a multi select draggable list based on the demo multi from this site. The source code of the controller and view is the same as the demo multi in this site. But console generates following logs:

Uncaught TypeError: $parse(...)(...) is not a functioninvokeCallback 
(anonymous function) @ bower.js:54291
dispatch @ bower.js:4435
elemData.handle @ bower.js:4121

Problem comes from directive 'dndList' and the following function

 function invokeCallback(expression, event, index, item) {
            if(expression) {
              return $parse(expression)(scope)(event, index, item || undefined, !dndDragTypeWorkaround.isDragging, dndDragTypeWorkaround.isDragging ? dndDragTypeWorkaround.dragType : undefined);
            }
        }

My view is like this: 

```
          <div ng-repeat="list in models" class="col-md-6">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title">List {{list.listName}}</h3>
                </div>
                <div class="panel-body">
                    <ul dnd-list="list.items" dnd-drop="onDrop(list, items, index)">
                        <li ng-repeat="item in list.items"
                            dnd-draggable="getSelectedItemsIncluding(list, item)"
                            dnd-dragstart="onDragstart(list, event)"
                            dnd-moved="onMoved(list)"
                            dnd-dragend="list.dragging = false"
                            dnd-selected="item.selected = !item.selected"
                            ng-class="{'selected': item.selected}"
                            ng-hide="list.dragging && item.selected">
                            {{item.label}}
                        </li>
                    </ul>
                </div>
            </div>
        </div>
```

I am using angular 1.5.3 with angular-drag-and-drop-lists 1.4.0

**Comment by madriman** [comment]
@ #

**Comment by marceljuenemann** [comment]
Sounds like onDrop is not defined on your scope? What's your code for that function?
