### ISSUE TITLE
Container with single column - Place children inside parent node (root)

### ISSUE THREAD

**Issue by thiagosoeiro** [marceljuenemann/angular-drag-and-drop-lists#312]
Even if containers have only one "column" of children, I noticed the model generates it inside another array with index 0, like this:
https://s9.postimg.org/pgudg4ssf/image.png

Is it possible to place children inside parent node, removing this "unnecessary" array? The model should look like this:
https://s13.postimg.org/qjbedgyk7/image.png

Is this achievable? How can this be done?
Thanks.

**Comment by marceljuenemann** [comment]
The model is entirely controlled by your code, the directive doesn't create any arrays or objects. You have to change the code that generates the model.

**Comment by erperejildo** [comment]
> The model is entirely controlled by your code, the directive doesn't create any arrays or objects. You have to change the code that generates the model.

@marceljuenemann I know this is too old already but despite I cannot see the images I think this is similar to the issue I'm facing, moving from [[]] to []. I tried to change my model but didn't work and I need to refactor also the html. Is there a simpler way maybe?
