### ISSUE TITLE
$apply already in progress error

### ISSUE THREAD

**Issue by andrewmadridista** [marceljuenemann/angular-drag-and-drop-lists#313]
if (transferredObject !== true) {
          scope.$apply(function() {
            scope.$eval(attr.dndList).splice(index, 0, transferredObject);
          });
        }
this block fires the error
I'am trying to implement nested lists with types. I have categories, products and subproducts. Like this:
categories = [
{
products: [
{
    ...
    subProducts: [
     { 
      ...
     }
   ]
  }
 ]
}
]
So i'am trying to create 3 drag&drop lists inside eatch other. and have such error, i think becouse my ul with dnd-list attr is already inside ng-repeat

**Comment by marceljuenemann** [comment]
Having three nested lists should work without problems. If you think there is a bug in the directive, can you create a jsfiddle/plunkr with the minimal code to reproduce it?
