### ISSUE TITLE
Separated containers

### ISSUE THREAD

**Issue by di3orlive** [marceljuenemann/angular-drag-and-drop-lists#315]
hi
I can't find answer to this question.
all examples that i found look like this

```html
models = {
    lists: {"A": [], "B": []}
};
<ul dnd-list="list">
    <li ng-repeat="item in models.lists" dnd-draggable="item"></li>
</ul>
```

so here all containers and items in one div 

and i need that they were separated

```html
models = {
    lists: {"A": [], "B": []}
};
<ul dnd-list="list">
    <li ng-repeat="item in models.lists.A" dnd-draggable="item"></li>
</ul>

<ul dnd-list="list">
    <li ng-repeat="item in models.lists.B" dnd-draggable="item"></li>
</ul>
```

is it possible ?

**Comment by marceljuenemann** [comment]
Yes, that's possible. The examples you are referring to are nested ng-repeats, i.e. one ng-repeat for all lists and then a nested ng-repeat that shows the items of the lists. It's essentially what you wrote in your second example just without the need to repeat your code.

**Comment by di3orlive** [comment]
yes 
but then i get errors ..
http://plnkr.co/edit/YDFPW98eQsnYXAhslPzI?p=preview

**Comment by marceljuenemann** [comment]
You forgot to modify the dnd-list attribute, i.e. dnd-list="models.lists.A"

**Comment by di3orlive** [comment]
oh...
tnx and sorry)
