### ISSUE TITLE
dnd-allowed-types in nested containers

### ISSUE THREAD

**Issue by captainmorgan0** [marceljuenemann/angular-drag-and-drop-lists#316]
I'm trying to modify the nested example:
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested

I would like to change it so only containers can be placed in the dropzone and only items can be placed in the containers. I changed the list.html to the following, but it doesn't work:

`<script type="text/ng-template" id="list.html">
                            <ul dnd-list="list" dnd-allowed-types="['container']">
                                <li ng-repeat="item in list"
                                    dnd-type="'container'"
                                    dnd-draggable="item"
                                    dnd-effect-allowed="move"
                                    dnd-moved="list.splice($index, 1)"
                                    dnd-selected="models.selected = item"
                                    ng-class="{selected: models.selected === item}"
                                    ng-include="item.type + '.html'">
                                </li>
                            </ul>
                        </script>`

**Comment by captainmorgan0** [comment]
Does anyone have a solution to this?

**Comment by marceljuenemann** [comment]
There's a demo that does this here: http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced

**Comment by itsmartyexpert** [comment]
@captainmorgan0 , Did you implemented this as per "marceljuenemann". I really need to this achieve.
If you have done this then please help on it. 
Thanks in advanced,
Jack R.

**Comment by AhmedMa3rouf** [comment]
any update of this issue,
