### ISSUE TITLE
dndDragover class is added/removed repeatedly on dragenter of child

### ISSUE THREAD

**Issue by mcMickJuice** [marceljuenemann/angular-drag-and-drop-lists#318]
When dragging element of a dropzone's child element, dragleave is fired even though dragovers continue to fire on dropzone element.  We use this class to style our dropzone element and it's causing the styling to flicker.
#317 fixes this issue using debounce and on resolution of the debounce method, both dndDragover class and the placeholder are removed.

**Comment by mcMickJuice** [comment]
hi @marceljuenemann would you be able to review this pending PR and merge when you get a chance? Thanks!

**Comment by marceljuenemann** [comment]
Already experimented with a new dragleave handler, but need to give it another attempt: Duplicate of #119
