### ISSUE TITLE
Creates Duplicates of Array Members Aren't Objects

### ISSUE THREAD

**Issue by danielstern** [marceljuenemann/angular-drag-and-drop-lists#32]
I noticed I got some very tricky behaviour involving duplicates if I used an array of strings like so,

`['a','b','c'];`

The problem went away when I used object literals:

`[{a:'a'},{b:'b'},{c:'c'}]`

It might make sense for the library to throw an error if it detects that a member of an array it is using is not an object.

**Comment by inca** [comment]
:+1: however, it makes _much_ more sense to support strings.

**Comment by marceljuenemann** [comment]
I think that's more of an angular restriction. If you use primitives in a ng-repeat it can't write a hash to it, therefore it can't distinguish equal elements. Try using track by $index:
https://docs.angularjs.org/error/ngRepeat/dupes

**Comment by inca** [comment]
Actually, I think it requires a bit of treatment from the library side.

This [plnkr demo](http://plnkr.co/FCKbia17UH9EiGgb7D4Y) shows that move backwards works incorrectly (the `dnd-moved="splice($index, 1)"` was written after original demos).

**Comment by marceljuenemann** [comment]
You're right, track by $index doesn't work either because angular always thinks only the last element changed. But still, this is a problem with ngRepeat, I don't think there's anything I can do about it:

**Comment by danielstern** [comment]
Maybe a quick check,

`if (typeof element == 'string') throw new Error('Drag and drop list elements must be objects.')`

**Comment by seiyria** [comment]
Definitely should be a warning or something - this caught me by surprise.
