### ISSUE TITLE
Multiselection Drag&Drop on mobile devices

### ISSUE THREAD

**Issue by peio72** [marceljuenemann/angular-drag-and-drop-lists#320]
Any chance to have the multiselection working with mobiles/tablets (or at least having multiselection on desktop and simple drag on mobile/tablets) ?

I tried with ios shim with no luck (not sure how to use it properly?)

If someone can help me and provide code sample it would be great.

Thanx.

**Comment by marceljuenemann** [comment]
HTML5 drag & drop support is pretty much non-existent on mobile. You'll need to try to make the ios shim work, unfortunately.
