### ISSUE TITLE
feature request - user specified index for item to be dropped

### ISSUE THREAD

**Issue by xmsalman** [marceljuenemann/angular-drag-and-drop-lists#321]
can user decide on which index the item should be dropped? in dnd-drop callback function, we return the item so that the item gets dropped in the list. likewise, do we have any way to provide the index on which the item should be dropped?

Say I want the item to be dropped only in index 3 even if its dragged to index 7.

**Comment by marceljuenemann** [comment]
The best UX would probably to disallow dropping to other positions using a dnd-dragover handler. Other than that you can also have dnd-drop callback that returns true and does the insertion to the list on its own.
