### ISSUE TITLE
The drop zone won't work if the dnd-list is an empty array?

### ISSUE THREAD

**Issue by ericxinzhang** [marceljuenemann/angular-drag-and-drop-lists#325]
In my scenario the drop zone initially is empty, so I created an empty array for the dnd-list. Then I noticed that angular-drag-and-drop-lists is not working - the dragover and drop callback are not called either. 

I created a plunker to demo this:

http://plnkr.co/edit/uMoA2bk1UB8gJVal6UAb?p=preview

It won't work until you open the scripts.js and add a empty object to the array. 

```
// This won't work
$scope.selectedProducts = [];
// The following line works
// $scope.selectedProducts = [{}];
```

**Comment by DriesMeerman** [comment]
You need to make sure that both the height and width of the dropzone is bigger than 0.
Like this http://plnkr.co/edit/u5WVu8mxkGWf8hcEEqoT?p=preview

**Comment by ericxinzhang** [comment]
Aha, that's the reason... thanks a lot @DriesMeerman

**Comment by gerome0123** [comment]
@ericxinzhang can you upload the working plunker i use your code for my reference and its help me a lot thanks

**Comment by ericxinzhang** [comment]
Hi @gerome0123, http://plnkr.co/edit/uMoA2bk1UB8gJVal6UAb?p=preview is a working version. The only change is following in style.css as per DiresMeerman's comment:
```
/* Newly added to make sure the empty dropzone is available for drop */
ul {
  height: 36px;
}
```
