### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setData' of undefined

### ISSUE THREAD

**Issue by simonaco** [marceljuenemann/angular-drag-and-drop-lists#326]
There seems to be a conflict between this library and jquery.event.drag-2.0.min.js. Drag and drop stops working with:

`Uncaught TypeError: Cannot read property 'setData' of undefined(anonymous function) @ angular-drag-and-drop-lists.js:93p.event.dispatch @ jquery-1.8.1.min.js:2(anonymous function) @ jquery.event.drag-2.0.min.js:6p.extend.each @ jquery-1.8.1.min.js:2p.fn.p.each @ jquery-1.8.1.min.js:2h.drag.hijack @ jquery.event.drag-2.0.min.js:6h.drag.handler @ jquery.event.drag-2.0.min.js:6p.event.dispatch @ jquery-1.8.1.min.js:2g.handle.h @ jquery-1.8.1.min.js:2`

when including jquery.event.drag-2.0.min.js. This library is required for the slick grid lib (https://github.com/mleibman/SlickGrid) 

Any workarounds for this issue? 

Thanks.

**Comment by jibax** [comment]
+1 Same problem, any idea ?

**Comment by marceljuenemann** [comment]
The jquery.event.drag library does not seem to be compatible with HTML5 drag & drop. It seems that they trigger a custom dragstart event, which is an event name that is also used by HTML5. IMO that is a very unfortunate choice for an event name. I don't think there is anything we can do until the library becomes compatible (i.e. does not break) HTML5 drag & drop apps.

**Comment by simonaco** [comment]
As mentioned in this article https://jasonturim.wordpress.com/2013/09/01/angularjs-drag-and-drop/, this could be a workaround:  

> I’m happy to say that it’s an issue with jQuery and you can resolve it by adding the following code when the page loads.
`jQuery.event.props.push('dataTransfer');`

**Comment by talbenbasat** [comment]
+1

**Comment by vincentism** [comment]
I came across similar problem, not with jquery but ionic, am not sure if it's compatibility issue, the console prints this: 

![96ef25cf-c522-498d-a791-e1959e73bde3](https://cloud.githubusercontent.com/assets/12859188/20911754/4599071c-bba5-11e6-8dcc-de5ad2eb7f59.png)
    
I wonder if someone has the same question, and ideas?

**Comment by simonaco** [comment]
@vincentism have you tried the workaround mentioned in the article i linked here? 

`jQuery.event.props.push('dataTransfer');`

on page load.

**Comment by vincentism** [comment]
@simonaco yes, i have tried, still not working. 

however, i noticed someone mentioned disable ion-content scrolling and has-bouncing,  this method works.

**Comment by cavanxatiniu42** [comment]
jQuery.event.props.push('dataTransfer');
where can i put this code?

**Comment by phoenixzqy** [comment]
@cavanxatiniu42 Just as @simonaco mentioned before, adding `jQuery.event.props.push('dataTransfer');`  to anywhere after jQuery lib loading and before you use `dragstart` start event.
