### ISSUE TITLE
 Is it possible to select an item automatically when it's dropped to the list?

### ISSUE THREAD

**Issue by thiagosoeiro** [marceljuenemann/angular-drag-and-drop-lists#329]
How can I automatically select an item when it's dropped to the list?
By default, it will not be select. Only I click it.

**Comment by marceljuenemann** [comment]
There is no such thing as "selection" in this directive. There's a dnd-selected callback, but you have to keep track of the selected element yourself. You can do that using a custom dnd-drop callback though.
