### ISSUE TITLE
Easily allow drag & drop with lists with duplicate items

### ISSUE THREAD

**Issue by toejough** [marceljuenemann/angular-drag-and-drop-lists#33]
[edit - I tried removing an item on dragstart to get around the duplicate item issue, and submitted this issue prior to really working with it and discovering some flaws.  The root issue is that the example model for using drag & drop with lists doesn't work with lists which are tracked by $index, as is the suggested solution for lists with duplicate items in them.]

If you remove an item on dragstart, that item doesn't stay displayed in the list while you drag.  It also removes it correctly in both the standard "ng-repeat x in y" and "ng-repeat x in y track by $index". 

The second example is what angular's error page tells you to try if you ever try to ng-repeat something with duplicate entries.

**Comment by toejough** [comment]
Nevermind - this is a bad idea (see comments for closing #34)

The best solution I've figured out so far is to add data to the model when dragging starts (like "item.dragged = true").  When dragging starts, I remove that property from everything in the list, and add it to the thing that is being dragged.  When "moved" is fired, I find the "dragged" item and remove that.
 
Regardless, it would be great to be able to use this plugin easily with lists with duplicate entries.  My current solution isn't difficult, but it took some thinking and wasn't obvious, and touches the actual item's data structure (which feels really dirty).  

Could you add better support for lists with duplicate items, or post a suggested method for dealing with them when using this module?

**Comment by toejough** [comment]
Another way I've gotten around this is to add UUID's to each of the items in the list (to differentiate any otherwise duplicate items, so that I don't have to track by $index).

**Comment by marceljuenemann** [comment]
I'd say this is an issue with ng-repeat, and not specific to this directive? Take a look at the ngRepeat documentation to find a better solution than creating a UUID yourself.
