### ISSUE TITLE
Lost select data binding when moving around element

### ISSUE THREAD

**Issue by BVJin** [marceljuenemann/angular-drag-and-drop-lists#331]
I have a list using the dnd list, and in each element UI, there is a select which has ng-model to bind data. The problem I dont understand is when I am moving around those elements, the select goes blank but the ng-model data is still in the element data, I don't know how to fix it, please help.

```

<div class="pull-left col-md-3">
    <select 
          ng-disabled="element.ElementIsLocked == 1"
          ng-model="element.speakerModel" 
          ng-options="summitSpeaker.Description for summitSpeaker in summitSpeakers | orderBy:'ItemID'"
          ng-change = "summitSpeakerChange(element,session)" 
          class="speaker-selector col-md-12 margin-l">
    </select>
</div>
```

I checked the element, the element.speakerModel does exist with correct data.

Thank you

**Comment by marceljuenemann** [comment]
Are you using a track by expression by any chance?

**Comment by BVJin** [comment]
@marceljuenemann I did use it.

I found the problem and fixed it. The problem I was using the Object(element.speakerModel) as the ng-model, as long as I change the ng-model to string, the select was not blank anymore.

I will close it.
