### ISSUE TITLE
Chrome 53.0.2785.143 m - No longer works with drag and drop lists

### ISSUE THREAD

**Issue by Deklin** [marceljuenemann/angular-drag-and-drop-lists#334]
Firefox and IE appear to be ok, chrome is broken. Even the samples on this website do not work, unable to drag anything around.

**Comment by Deklin** [comment]
Closing, This is fixed in chrome 55 (tested with chromium)

**Comment by uptonking** [comment]
@Deklin 
drag and drop doesn't work with chrome 58.0.3  on CentOS 7.2 again.
will you fix it?

**Comment by Deklin** [comment]
Last time it was a browser defect with html5 drag and drop, not an issue with this library.

**Comment by uptonking** [comment]
@Deklin 
your `angular-drag-and-drop-lists` lib is based on AngularJS 1. 
does it support Angular 2 or 4?  I haven't test it.
if not, do you have any plan to update it?

**Comment by Deklin** [comment]
@uptonking this is not my library or module, I was just someone who wanted to contribute. @marceljuenemann owns this repository.
