### ISSUE TITLE
Question: List items on event dnd-dragstart

### ISSUE THREAD

**Issue by bartonsprings** [marceljuenemann/angular-drag-and-drop-lists#337]
I am trying to make a deep cloning of the list just before the dragging event starts. This is for the case of UNDOING the move in case something fails in the backend processing etc. 

Are the list items still in original state and not modified on this event dnd-dragstart and can I safely make a backup copy of the list on this event and ensure the original items are present and no additional item is added to the list by this library at this point? I can see that on dnd-moved event there are extra items in the list so just wanted to be sure. 

Thanks!

**Comment by marceljuenemann** [comment]
The directive doesn't modify any of your models, except for inserts on drop. Any other modifications are up to you by using callbacks, e.g. dnd-moved
