### ISSUE TITLE
Placeholders/Dropzones to appear on 'Dragstart'

### ISSUE THREAD

**Issue by willramos** [marceljuenemann/angular-drag-and-drop-lists#339]
When I drag an item,

I want to be able to visually see the dropzones/placeholders above and below every list item on the dnd list. This would make it clearer to our users where to place the draggable item. 

Can you have this developed into angular-drag-and-drop-lists in the near future?
Or, is there any way to accomplish this now? 

Thanks in advance

**Comment by marceljuenemann** [comment]
You can definitely do this now either on dnd-dragover or dnd-start. You would have to set some CSS class and then you can have some visual indication with :before and :after
