### ISSUE TITLE
get the item Im over on before dropping on it

### ISSUE THREAD

**Issue by stephschuster** [marceljuenemann/angular-drag-and-drop-lists#340]
I want to know if there is a way to know over which item Im on (when ever the css dndDragover is on). 
Or even better, is there a solution to change the ghost css when Im over a 'not-allowed' item?
Im trying to change my ghost div when Im over a not-allowed item but I dont know how to get the item Im over on

**Comment by marceljuenemann** [comment]
One basic thing to keep in mind is that your not dropping over a list item, but instead between two list items. The dnd-dragover callback does have a index variable you can use. However, the normal UX for native drag and drop is that disallowed target elements don't change at all.
