### ISSUE TITLE
Dragged Item Not Displaying on Drag

### ISSUE THREAD

**Issue by sidneyphillip** [marceljuenemann/angular-drag-and-drop-lists#341]
Within the demos I can not see the item while dragging. It basically turns into this gray square. I also can not see the custom image display for the Multiselection demo. Is this the expected result? Thanks.

![image](https://cloud.githubusercontent.com/assets/13981071/19664253/93acd4a6-9a0d-11e6-93c0-9e44b30cffd1.png)

![image](https://cloud.githubusercontent.com/assets/13981071/19664331/d7393b88-9a0d-11e6-8fa3-3c05e61de39b.png)

**Comment by marceljuenemann** [comment]
What browser are you using?

**Comment by marceljuenemann** [comment]
I can't reproduce that. Are you simply viewing the demo page? Which OS and which Chrome version are you using?

**Comment by marceljuenemann** [comment]
Feel free to reopen if issue is still there. I tested on various OS and browsers yesterday though without issues.
