### ISSUE TITLE
saving the new order back to model

### ISSUE THREAD

**Issue by stelco** [marceljuenemann/angular-drag-and-drop-lists#343]
Hi. Once Ive dragged elements into their new position, they are not saved.  A page refresh reverts back to the original order. We are using angular ng-repeat to load the data.  Is there any documentation on saving the new order back to the model? Currently the form which saves the data looks like this. Do we need to be saving the index..? Any advice appreciated.  Thanks.

@using (Html.BeginForm(MVC.Cruise.SaveLine(), FormMethod.Post, new { line = Model, data_ng_app = "linesApp", id = "form", name = "form", role = "form", data_ng_submit = "form.$valid && vm.submit($event)", novalidate = "", data_ng_controller = "linesCtrl" }))

**Comment by marceljuenemann** [comment]
Persisting changes is up to you. I recommend using either $watchCollection or the dnd-drop callback to trigger saving your model.
