### ISSUE TITLE
Nothing render

### ISSUE THREAD

**Issue by desatir7316** [marceljuenemann/angular-drag-and-drop-lists#345]
I used exactly the same code in simple and other example but it renders nothing. For example this is the code for simple example:
JS:

`$scope.models = {
            selected: null,
            lists: {"A": [], "B": []}
        };

        // Generate initial model
        for (var i = 1; i <= 3; ++i) {
            $scope.models.lists.A.push({label: "Item A" + i});
            $scope.models.lists.B.push({label: "Item B" + i});
        }

        // Model to JSON for demo purpose
        $scope.$watch('models', function(model) {
            $scope.modelAsJson = angular.toJson(model, true);
        }, true);
`

HTML:

`
<ul dnd-list="list">

        <li ng-repeat="item in list"
            dnd-draggable="item"
            dnd-moved="list.splice($index, 1)"
            dnd-effect-allowed="move"
            dnd-selected="models.selected = item"
            ng-class="{'selected': models.selected === item}"
        >
            {{item.label}}
        </li>
    </ul>`

And finally it renders this.

`<ul dnd-list="list">
        
    </ul>`

**Comment by keithmichelson** [comment]
The sample code is wrong. 

In the html, "list" should be "models.lists"

**Comment by vipulpandeykv** [comment]
Still nothing is rendering

**Comment by marceljuenemann** [comment]
The sample code is only for one list, while the JavaScript snippet generates the models for all lists. I recommend you to not copy & paste any code, you will not understand how a library works that way. Instead, start by coding a non-draggable list the way you want it in your application. Once you can see it on screen, start adding a dnd-draggable tag, and next a dnd-list.
