### ISSUE TITLE
Drop not working when I using dragover

### ISSUE THREAD

**Issue by CLenon** [marceljuenemann/angular-drag-and-drop-lists#347]
Hi,

Thanks for this directive you made, is amazing and it help me a lot. I have been having some trouble with the drop behavior and the dragover behavior. I'm asking myself if i'm doing something wrong or it is an issue.

This the code example. Can some one please tell me what i'm doing wrong. Thanks

[Gist link](https://gist.github.com/CLenon/9d4187bc2911a370aa8b3d7a576868c8)

**Comment by marceljuenemann** [comment]
It looks like you're not setting the function on your angular scope. Thus, it can't find the method and thinks it returned undefined, therefore cancelling the drop.
