### ISSUE TITLE
After Dropping item from list anchor tag gets removed

### ISSUE THREAD

**Issue by azadacme** [marceljuenemann/angular-drag-and-drop-lists#349]
I have attached anchor tag to item at run time. After dragging and dropping, items is dropping at desired place but anchor tag gets removed i.e. text content is updated and reordered but other tags like anchor, bold, italic etc gets removed after dropping item. Is there any solution on this?

**Comment by azadacme** [comment]
Before Dragging and Dropping:-
![issue1](https://cloud.githubusercontent.com/assets/12965237/19995051/a8634352-a279-11e6-9fe7-34e95959f853.png)

After Dragging and Dropping:-
![issue2](https://cloud.githubusercontent.com/assets/12965237/19995056/b38d151e-a279-11e6-8678-32798b1fb572.png)

**Comment by marceljuenemann** [comment]
The directive doesn't transfer the DOM element, it just transfers an object from your model. The angular best practice is to avoid directly modifying the DOM, instead you should have the anchor tag in your template and conditionally add it with ng-if etc.
