### ISSUE TITLE
Item duplicated after drop in the same list (second item into first position)

### ISSUE THREAD

**Issue by jjsjunior** [marceljuenemann/angular-drag-and-drop-lists#351]
Using angular-drag-and-drop-lists version 1.4 with angular 1.5.0
After dropping a item on the same list (second item into first position - Choosen fields) the second item becomes duplicated on the model.
Does anybody had the same problem?

JsFiddle: [jsfiddle](https://jsfiddle.net/jhw5zjwm/5/)

![issue](https://cloud.githubusercontent.com/assets/20688528/20106440/4a0cd5e8-a5bc-11e6-9a7b-a000979ddf00.png)

**Comment by louiszhu2zgf** [comment]
have you fixed it?@jjsjunior
