### ISSUE TITLE
It just duplicates the item

### ISSUE THREAD

**Issue by bendspoons** [marceljuenemann/angular-drag-and-drop-lists#353]
This simple setup does no work, it just duplicates the dragged item to the dropped position. 

selectedData is a simple array, in which are several entries.

`[{
    "id": "1",
    "title": "One",
    "order_by": "1"
},
{
    "id": "2",
    "title": "Two",
    "order_by": "3"
},
{
    "id": "3",
    "title": "Three",
    "order_by": "3"
}]`

`<ul dnd-list="selectedData">`
`<li ng-repeat="presentation in selectedData" dnd-draggable="presentation">`
`{{presentation.title}}`
`</li>`
`</ul>`

Did i misunderstood the whole purpose of this plugin?

**Comment by ksgupta** [comment]
If you move the item to a position below, it would not duplicate I guess, while moveing an item up in order, it simply removes the item below the picked up position and duplicates the picked up position in the list. Is that what you are experiencing too?

**Comment by kirea** [comment]
I've got the same problem. 
If I drag an item up through the list and drop it, the item that is below dropped one, is dissappearing and substituting with the dropped item. At the same time the dropped item leaves in the old position too, so it simply duplicates.
But I drag an item down through the list, everything is ok.

**Comment by stuartsoft** [comment]
Can also confirm, the behavior of moving items within a single list does seem to cause issues with it duplicating items.

**Comment by gingman** [comment]
I had this problem when using `track by`on my `ng-repeat`. Remove it fixed the problem.

**Comment by Fossil01** [comment]
Ran into this problem as well. Now battling another issue #310 

Maybe the code from the fiddle will help you?

**Comment by bryangrimes** [comment]
Had the same issue with a single list over the past day or so as well.  `track by` wasn't being used in my case, just a simple repeat as well which is a huge issue for single list usage.

**Comment by marceljuenemann** [comment]
Moving items is just one use case for drag and drop. If you want to move items, you'll need to add a dnd-moved handler as seen in the examples.

**Comment by louiszhu2zgf** [comment]
@gingman but remove track by will cause angular duplicate repeat error

**Comment by AlexTimofeyev** [comment]
Hm, strang, I change method "onDrop" 
And, items not removed.

$scope.onDrop = function(list, items, index) {
      // Deselect all previously selected items after dropping them in a list
     angular.forEach(items, function(item) {        
        item.selected = false;    
     });    	
      $scope[list].users = $scope[list].users.slice(0, index)
                  .concat(items)  
                  .concat($scope[list].users.slice(index));
      return true;
    }
