### ISSUE TITLE
Mouse offset issue when sub-node of draggable

### ISSUE THREAD

**Issue by eddow** [marceljuenemann/angular-drag-and-drop-lists#359]
When the draggable item contains a more complex structure, the function "isMouseInFirstHalf" has an erroneous behaviour (chrome)
As the object is dragged-over a sub-node of the draggable listitem, the "offset[X/Y]" is calculated on the sub-node, not on the draggable item.
I can become a big issue when the "second half" of the item is inexistant and we wish to move an item at the end of the list.

```
<li dnd-draggable>
 <div>I am the first half</div>
 <div>I am the first half too!!</div>
</li>
```

**Comment by bra1n** [comment]
#319 seems to be about the same problem

**Comment by eddow** [comment]
Indeed. I didn't find it when looking around :-/ This one should be marked as duplicate.

**Comment by marceljuenemann** [comment]
Please take a look at the new v2.0, this should be fixed now.
