### ISSUE TITLE
Drag doesn't work nomally when handing File Object.

### ISSUE THREAD

**Issue by qwefgh90** [marceljuenemann/angular-drag-and-drop-lists#362]
Hello.

I use this library to sort a list of files which will be uploaded to server.

After dragging any file, "undefined" is assign to a element in list.

I think file object cannot be serialized. 

I tested it with JSON.serialize and It just returned empty Object {}.

Is there way to use list of File Object?

Thanks!

**Comment by qwefgh90** [comment]
Roughly, to solve this problem, I used the following code example.

I used some fields to be serialized / deserialized. Later, It's looking for same file.

![solution](https://cloud.githubusercontent.com/assets/7572251/21350703/0e1567e2-c6fc-11e6-9573-6b0ad81d72f3.png)

**Comment by marceljuenemann** [comment]
File objects don't work due to the serialization that the directive performs. You can solve this with the new dnd-callback, e.g. https://jsfiddle.net/Ldxffyod/1/
