### ISSUE TITLE
cannot read property splice of undefined

### ISSUE THREAD

**Issue by johannesjo** [marceljuenemann/angular-drag-and-drop-lists#367]
When using this example, when dropping an item very often the error `cannot read property splice of undefined` appears:
http://plnkr.co/edit/YDFPW98eQsnYXAhslPzI?p=preview

**Comment by sam-g-roberts** [comment]
I'm also receving this error since upgrading to angular 1.6 when reordering items.

final-1b331c09bf.js:14328 TypeError: Cannot read property 'splice' of undefined

angular#1.6.1
angular-drag-and-drop-lists#1.4.0

**Comment by ChaudhryAtif** [comment]
Based on this SO, http://stackoverflow.com/questions/35263268, the 'list' in dnd-list="list" is undefined. It should change to the list you repeating over (i.e. 'models.lists.A' and 'models.lists.B' respectively).

Plunkr: http://plnkr.co/edit/OWwDCaYUjuN7fM5y5Btd?p=preview

**Comment by marceljuenemann** [comment]
The plnkr in OP is indeed wrong as it uses a undefined list.

@sam-g-roberts If you can consistently reproduce the bug, can you create a jsfiddle / plnkr and create a new issue?
