### ISSUE TITLE
Implement multi-drag and drop

### ISSUE THREAD

**Issue by nthibert** [marceljuenemann/angular-drag-and-drop-lists#37]
Wondering if it would be possible to implement multi-drag and drop. Since the select is already there, could it keep track of the items selected?

**Comment by zorzysty** [comment]
+1

**Comment by hjansen** [comment]
+1

**Comment by marceljuenemann** [comment]
Sorry, native drag & drop does not support multi-drag and drop. It's surely possible in pure JavaScript, although not very easy.
