### ISSUE TITLE
Directive not rendering

### ISSUE THREAD

**Issue by yevgetman** [marceljuenemann/angular-drag-and-drop-lists#370]
Im trying to implement a simple drag and drop case but its not rendering:

`<script src="../angular.min.js"></script>`

`<script src="http://marceljuenemann.github.io/angular-drag-and-drop-lists/angular-drag-and-drop-lists.js"></script>`

`<div class="btn" dnd-draggable >test</div>`

Result is a standard element which is not draggable

**Comment by marceljuenemann** [comment]
You need to provide at least *some* data that can be dragged. `dnd-draggable="null"` should be enough.
