### ISSUE TITLE
dndType is converted to lower case

### ISSUE THREAD

**Issue by sierraindiagolf** [marceljuenemann/angular-drag-and-drop-lists#372]
Hello,

After investigating i found that `dndState.itemType = attr.dndType && scope.$eval(attr.dndType).toLowerCase();` converts the value provided to dnd-type to lowercase.

Is there a special reason for converting the dnd-type attribute to lowercase in version 2 ?

**Comment by marceljuenemann** [comment]
From version 2 the type is sent as mine type, which it's always lowercase according to the standard. This is so that dnd-type works also with dnd-external-sources. Should have probably added a note to the change log, thanks for the hint.

**Comment by marceljuenemann** [comment]
Added this to the changelog.
