### ISSUE TITLE
Error on 'dragstart' listener <Cannot read property 'setData' of undefined>

### ISSUE THREAD

**Issue by vTrip** [marceljuenemann/angular-drag-and-drop-lists#374]
Getting an error when starting drag action

```
angular-drag-and-drop-lists.js:112 Uncaught TypeError: Cannot read property 'setData' of undefined
at HTMLElement.<anonymous> (angular-drag-and-drop-lists.js:112)
at HTMLElement.dispatch (jquery.min.js:3)
at HTMLElement.r.handle (jquery.min.js:3)
at ionic.Gestures.Instance.triggerEvent [as trigger] (ionic.bundle.js:822)
at Object.dragGesture [as handler] (ionic.bundle.js:1866)
at Object.detect (ionic.bundle.js:1400)
at HTMLDocument.bindDomOnTouch (ionic.bundle.js:949)
```

**Comment by marceljuenemann** [comment]
Sounds like a problem with ionic.bundle.js not correctly mocking the event as specified by the HTML5 standard.

**Comment by vTrip** [comment]
have you come across any stable implementations with an Ionic application ? @marceljuenemann

**Comment by marceljuenemann** [comment]
You should probably ask on the ionic forum about how the framework works together with HTML5 drag and drop. It seems they are using the dragstart event somehow, but there is a problem of dataTransfer not being defined on that event.

**Comment by marceljuenemann** [comment]
Confirming what I said, ionic has it's own gesture module that triggers dragstart events: https://gist.github.com/mhartington/909f573627d0e8ba3bdd#file-ionic-bundle-js-L8711

As these events are not compatible with the dragstart events defined in the HTML5 standard, this means ionic can not be used together with HTML5 drag & drop (at least not on the same elements).
