### ISSUE TITLE
How can i delete/remove item without draging into trash?

### ISSUE THREAD

**Issue by bpbhat77** [marceljuenemann/angular-drag-and-drop-lists#38]
This is a question.
I am using nested demo. I want to delete a perticular item from the list.
And i will be having 1 button for delete?

How can we delete a single item?

**Comment by jameswyse** [comment]
You can use the same `list.splice($index, 1)` code from the demo in your button! Just replace `$index` with the index of the item you wish to delete! 

```javascript
<button type="button" ng-click="list.splice(0, 1)">Delete the first item</button>
```

**Comment by bpbhat77** [comment]
@jameswyse  Works perfect.
