### ISSUE TITLE
"Touch" - device issue

### ISSUE THREAD

**Issue by simplifyod** [marceljuenemann/angular-drag-and-drop-lists#396]
Don't work on mobile device. Event after added 'touchstart' event here:

        element.on('click touchstart', function(event) {
           if (!attr.dndSelected) return;
           event = event.originalEvent || event;
           scope.$apply(function() {
             $parse(attr.dndSelected)(scope, {event: event});
           });
           // Prevent triggering dndSelected in parent elements.
           event.stopPropagation();
        });

**Comment by pieecia** [comment]
Did you use shim as it is mentioned in readme? 

> Touch devices are not supported, because they do not implement the HTML5 drag & drop standard. However, you can use a shim to make it work on touch devices as well.
