### ISSUE TITLE
how i can use this in an asp.net mvc application?

### ISSUE THREAD

**Issue by saleh313k** [marceljuenemann/angular-drag-and-drop-lists#398]
Hi, Thanks for your support
Can I use **angular-drag-and-drop-lists** in an asp.net MVC project?
I'm using visual studio, and before it, I was using JQuery , however I'm beginner in AngularJS

Please help me if you can
Thanks alot

**Comment by tdekoekkoek** [comment]
You can use any JavaScript library in ASP.NET MVC.  You simply need to include the required JavaScript includes in your index.cshtml and then include the necessary script sections in whatever .cshtml files you are using in your application.  At the end of the day, ASP.NET MVC is html and wherever the markup for this widget belongs, goes in the markup section of your pages.
