### ISSUE TITLE
Drag new items

### ISSUE THREAD

**Issue by forza020** [marceljuenemann/angular-drag-and-drop-lists#41]
Hello,

First of all, thank you for your wonderful directive. Just wondering any plans to make it work in conjunction with draggable elements. Something like jQuery already has. http://jqueryui.com/draggable/#sortable

Thank you.

**Comment by marceljuenemann** [comment]
Not sure if I understand the question, but I think what you want is already there:
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/nested
On the right side there is a "New Elements" box which does exactly what's in the demo that you linked.
