### ISSUE TITLE
Drop on address bar should not be allowed

### ISSUE THREAD

**Issue by cmjacques** [marceljuenemann/angular-drag-and-drop-lists#42]
Hi there and thanks for making this great directive.

I noticed that I can drop items on the browser's address bar and in Chrome this redirects the user away from your page.
Firefox and IE behave a little better - you can still drop on the address bar, but they won't redirect the user.

I had a look at [angular-ui-tree](http://jimliu.github.io/angular-ui-tree/) and it does not allow you to drop on the address bar. In fact it looks like you can't drag items out of the viewport at all.

It would be great if the drop event was cancelled if the user (accidentally) drops on the address bar.

Thanks

**Comment by marceljuenemann** [comment]
Nothing we can do here with native drag & drop, unless IE starts supporting other mime types than text/plain. If you don't care about native drag & drop, you can use angular-ui-tree, it's a great directive as well.

**Comment by cmjacques** [comment]
Ah - gotcha. Thanks for the explanation.
