### ISSUE TITLE
Could we have an Angular 2 version ?

### ISSUE THREAD

**Issue by simonmicheal** [marceljuenemann/angular-drag-and-drop-lists#422]

**Comment by tdekoekkoek** [comment]
+1 for Angular 2/4.  This looks really nice.

**Comment by imilic1** [comment]
+1 for Angular 4.

**Comment by ricetrac** [comment]
+1 for Angular 2/4

**Comment by marceljuenemann** [comment]
See #229, not planning to port this, but happy to link any forks that people create

**Comment by mcblum** [comment]
@marceljuenemann crap :( this is such a solid, flexible library and we've moved to Angular 4 and would love to be able to use it. Thanks for all of the work on this!

**Comment by heitorb** [comment]
Wow. Such a nice library. Way better than anything out there... too bad no Angular 2,4,5,6 support. Even google is dropping support for AngularJS soon. Did anyone here find any other like this one that has Angular x support?
