### ISSUE TITLE
Need to specify a callback when dragging an element ended but it was not dropped on a list of interest

### ISSUE THREAD

**Issue by bitliner** [marceljuenemann/angular-drag-and-drop-lists#43]
Let's say that I have 2 lists: I can drag an element from the first and drop it on the second list.

I would like to invoke a callback when an element is dragged from the first list but then it is dropped not on the second list, but on an external element (neither list1, neither list 2).

Apparently there actually is no such event, right?

**Comment by marceljuenemann** [comment]
That sounds like a really specific use case, maybe use the dragend event directly?
https://developer.mozilla.org/en-US/docs/Web/Events/dragend
