### ISSUE TITLE
Drag and drop item index is not in consistency 

### ISSUE THREAD

**Issue by jeevajsb** [marceljuenemann/angular-drag-and-drop-lists#44]
When move items from down to up, for example move last item to the first, then on callback index gives 0. So I understood that, the items ordered based on zero based index..

When I move first element to second place, then on callback the index should be 1. But on callback I am getting 2 instead of 1 for index.

Do I need to add anything to resolve this issue ?

**Comment by jameswyse** [comment]
I had trouble with this too, I think it's because the callback runs before splice has removed the old item.

In the end I used lodash and something like this:

```javascript
vm.navDragEnd = function (event, index, item, external, type, parent) {
  $timeout(function () {
    var idx = _.findIndex(list, function (node) {
      return node.id === item.id;
    });
  }, 1000, false);
```

(the `1000`ms may not be necessary, try with `null` or a lower number)

**Comment by marceljuenemann** [comment]
Yes, it's because the old element is still there, you just hid it with CSS. Note that in some cases this is what you want, e.g. when copying instead of moving. Therefore, I don't see a fix for this. Not sure what your use case is, but I'd avoid using the index whenever possible and rather manipulate the object.

**Comment by jeevajsb** [comment]
Can you provide the class name for the Old element which need to be hide?

But in example, I've seen like to remove (splice) and insert $index has been used. From that I understood, that's the position of the element.
