### ISSUE TITLE
Draggable items limitation.

### ISSUE THREAD

**Issue by EdAtomicRaccon** [marceljuenemann/angular-drag-and-drop-lists#446]
In the advanced demo (and also in the code I'm writing right now), when you have a too many items in the list, you cannot drop the items at the end of the list.

<a href="https://gyazo.com/6feba3cc2bf69f141023e11958ea48fe"><img src="https://i.gyazo.com/6feba3cc2bf69f141023e11958ea48fe.gif" alt="https://gyazo.com/6feba3cc2bf69f141023e11958ea48fe" width="1600"/></a>

Any workaround?

**Comment by warlockdn** [comment]
did you find any solution to this ?
