### ISSUE TITLE
For some reason this has slowed way down

### ISSUE THREAD

**Issue by mcblum** [marceljuenemann/angular-drag-and-drop-lists#448]
We're using this awesome package in a few different places in our app, and for the life of me I can't figure out why a couple of the implementations are really slow. Has anyone noticed that some of their drag and drop implementations don't work very smoothly? Maybe CSS or images are slowing it down?

Thank you for any insight.

**Comment by aidenZhou** [comment]
I encountered this issue recently as well. I am using this package to allow user to drag and drop different questions in a form. Recently one of our user created a form with around 140 questions. Now when he did drag and drop, it is very slow. It this normal? Thank you.

**Comment by pdemilly** [comment]
Same problem here. I reduce in my app to the simplest list and after a while of moving elements around I am getting some violation.  Also I am getting duplicates in my list

[Violation] 'drop' handler took 191ms
[Violation] 'dragend' handler took 337ms
[Violation] 'drop' handler took 1322ms
[Violation] 'dragend' handler took 2357ms
[Violation] 'drop' handler took 5557ms

And finally a crash telling me the browser was going to get out of memory. I am running angular 1.6.4 with ngAnimate loaded. Here is the HTML.

`div class="panel">
        <div class="panel-body">
                <ul class="list-group" dnd-list="vm.lists.A">
                        <li ng-repeat="item in vm.lists.A"
                                dnd-draggable="item"
                                dnd-moved="vm.lists.A.splice($index, 1)"
                                dnd-effect-allowed="move"
                                dnd-selected="vm.selected = item"
                                class="list-group-item"
                                ng-class="{'selected': vm.selected === item}">
                                {{item.label}}
                        </li>
                </ul>
        </div>
</div>

<div class="panel">
        <div class="panel-body">
                <ul class="list-group" dnd-list="vm.lists.B">
                        <li ng-repeat="item in vm.lists.B"
                                dnd-draggable="item"
                                dnd-moved="vm.lists.B.splice($index, 1)"
                                dnd-effect-allowed="move"
                                dnd-selected="vm.selected = item"
                                class="list-group-item"
                                ng-class="{'selected': vm.selected === item}">
                                {{item.label}}
                        </li>
                </ul>
        </div>
</div>
`

**Comment by poppahorse** [comment]
@mcblum @aidenZhou @pdemilly did you ever resolve this?

**Comment by abtx** [comment]
Has this been resolved? Doesn't seem like anyone is maintaining this anymore :/

**Comment by technoSpino** [comment]
I come from the future to tell you that no this will not be resolved
