### ISSUE TITLE
Scrolling when reaching border of browser window

### ISSUE THREAD

**Issue by hjansen** [marceljuenemann/angular-drag-and-drop-lists#45]
In other browsers than Chrome the browser window will not start to scroll when you reach the border of the browser window with an dragged element at you mousepointer.

There is an implementation for the standard jquery DnD implementation which might give some hints about how to implement this behaviour.

https://github.com/martindrapeau/jQueryDndPageScroll

**Comment by marceljuenemann** [comment]
I don't think that should be part of the core directive, since it's a lot of code and bloats the DOM with hidden elements. Good to know that exists though.

**Comment by none-da** [comment]
I found that even in Chrome it doesn't auto-scroll. Am I missing something ?
