### ISSUE TITLE
dnd-handle is not working

### ISSUE THREAD

**Issue by wiadev** [marceljuenemann/angular-drag-and-drop-lists#455]
@marceljuenemann 
Hi
Thanks for the great library.
I'm going to use dnd-handle but it's not working.
I'm going to move round with icon-move only but I can still drag and drop the whole item.

I've tested your sample code on my localhost but it's not working as well.

Any ideas?

Thanks

**Comment by oksas** [comment]
For anyone else that ended up here after having a similar issue... the problem for me seemed to be that the handle only worked if the element with `dnd-handle` on it was a direct child of `<dnd-nodrag>`. If the handle was nested within other elements, though, it didn't work :(

**Comment by wiadev** [comment]
@oksas it works, now. Thanks.
