### ISSUE TITLE
any tips for drag multiple items at once?

### ISSUE THREAD

**Issue by aaronloe** [marceljuenemann/angular-drag-and-drop-lists#47]
I'm combining this directive with another jQuery library for selecting multiple items at once (via ctrl+click, shift+click etc. See https://evulse.github.io/finderSelect for example). 

Is there a straight-forward way for telling dndLists to grab all other items that are currently decorated with a particular css class or json object property ? The idea is I should be able to click on any number of child items in my list of draggables to highlight them, and as I drag any one highlighted item, all highlighted items are dragged with it.

FYI I'm using  dnd-draggable inside an li with ng-repeat. 

Any help would be greatly appreciated. Thanks!

**Comment by marceljuenemann** [comment]
Sorry, the HTML5 drag & drop API does not support dragging multiple elements. This would require a pure JavaScript implementation.

**Comment by marceljuenemann** [comment]
I added a demo for how to do multiselect:
http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/multi

It tricks out the HTML5 API a bit by sending the data for all selected elements and then replacing the drag image with a custom one, so that you don't only see the dragged element.

**Comment by shruti12345** [comment]
@marceljuenemann Is there any link for multiselect using angular 4?

**Comment by fermdp** [comment]
Can you use flat html to put data in the lists? For example <a href="https://www.url.com/html/">Visit my url</a>
Thanks in advance!
