### ISSUE TITLE
Remove dnd-selected

### ISSUE THREAD

**Issue by cmlenz** [marceljuenemann/angular-drag-and-drop-lists#51]
The selection of draggable elements does not belong here in my opinion. It doesn't seem to do anything that can't be done with a simple `ng-click` instead. Am I overlooking something?

I propose it should be removed (for 2.0 as it'd be a breaking change). What do you think?

**Comment by marceljuenemann** [comment]
See other comment, stopPropagation is needed for nested lists. Otherwise you would be right.
