### ISSUE TITLE
How to add new items only to the end of list?

### ISSUE THREAD

**Issue by Deliaz** [marceljuenemann/angular-drag-and-drop-lists#53]
Hi!
I use code similar to [advanced demo](http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced).
But I need to add new items only to the end of the List. 
How can i implement this?

**Comment by theclapp** [comment]
I am not the author of this package and discovered it perhaps 30 minutes ago.  But your issue caught my eye.

I'd guess you could either use dnd-dragover to only allow adding at the end of the list (return false if not at end, the way the advanced demo doesn't let you drop stuff at the front of the list), or write the dnd-drop callback to ignore the given index and always add items to the end of the list.

**Comment by Deliaz** [comment]
@theclapp Thanks. I'll try implement your ideas when go back to work on UI.
