### ISSUE TITLE
Disable draggable when click a form in the list element

### ISSUE THREAD

**Issue by jeffjzx** [marceljuenemann/angular-drag-and-drop-lists#57]
I have put a text form in each element in the list. When i select the list element itself, it can be dragged as expected. However, when i want to select the text inside the text form (inside the list element) it cause the drag effect instead of selecting the text. How can i disable drag effect when i click text form?

**Comment by janbaykara** [comment]
+1

**Comment by Carw** [comment]
+1

Is there any idea how to fix it?

**Comment by karthim** [comment]
In all the examples, the li elements are set to be draggable(i.e., anything which is a child of li will get the drag event). You will have to seperate out the draggable portion from content portion. The following code snippet might help you.

```
<ul dnd-list="list">
        <li ng-repeat="item in list">
			<div class="header" 
				dnd-draggable="item"
				dnd-effect-allowed="move"
				dnd-moved="list.splice($index, 1)"
				dnd-selected="models.selected = item"
				ng-class="{selected: models.selected === item}"
				ng-include="item.type + '.html'">
			</div>
			<div class="content"> 
				<textarea rows="4" cols="50" ng-model="item.content">
				</textarea>
			</div>
		</li>
    </ul> 
```
 I followed this post http://stackoverflow.com/questions/13017177/selection-disabled-while-using-html5-drag-and-drop and implemented it.

Also you may have to change the pointer events in the css to enable the mouse events for selecting text.

**Comment by i3lackstorm** [comment]
the code above works for me. But, it would be nice to also include textarea in the drag effect. So, the text area follows when dragging the header. Any idea how?

**Comment by ryancrisp** [comment]
+1.  Would like to be able to select text in an input while still being able to drag the entire element if trying to drag from any other point.

**Comment by twmulloy** [comment]
+1

**Comment by marceljuenemann** [comment]
Had a look at this. Since the input is not draggable, the dragstart event will be triggered directly on the li, i.e. event.target is not set to the input element. A hack is to make the input element draggable="true" and then add this code to the directive:

    element.on('dragstart', function(event) {
        event = event.originalEvent || event;

        if (event.target.tagName === 'INPUT') {
          // Don't disable dragging if a selected text is being dragged.
          if (!(event.dataTransfer.types && event.dataTransfer.types.length)) {
            event.preventDefault();
          }
          return;
        }
        ...

Also in dragend add:

      element.on('dragend', function(event) {
        event = event.originalEvent || event;
        if (event.target.tagName === 'INPUT') return;
        ...

This worked pretty well in my test, but obviously very hacky. I think the best solution is to add a dnd-nodrag directive that can be used inside dnd-draggable to prevent dragging. With that there might also be no need for a handle directive anymore.

**Comment by marceljuenemann** [comment]
I've added a dnd-nodrag directive to the dev branch, you can try the [demo](http://marcel-juenemann.de/tmp/angular-drag-and-drop-lists-dev/). I'll merge it to master once I have tested it thoroughly.

**Comment by phanigokaraj** [comment]
You can just use <dnd-nodrag> your code </dnd-nodrag> now for the elements you wish to diasable drag effect
