### ISSUE TITLE
2 Suggestions

### ISSUE THREAD

**Issue by robinkedia** [marceljuenemann/angular-drag-and-drop-lists#58]
1. Can we tilt the item being dragged little. 
http://www.w3schools.com/cssref/tryit.asp?filename=trycss3_transform

2. Find the height of item being dragged and set the height of dndplaceholder accordingly.

**Comment by robinkedia** [comment]
Can you also put an example with dnd-handle. How to make drag complete container using specific portion.

**Comment by marceljuenemann** [comment]
1. The directive does not set any CSS, you can control it completely yourself.
2. If you have a use case where some elements are huge (e.g. deeply nested elements), then this is probably not what you want.
3. dnd-handle is not yet part of the directive.
