### ISSUE TITLE
Container with single child

### ISSUE THREAD

**Issue by shyamsalimkumar** [marceljuenemann/angular-drag-and-drop-lists#60]
Right now Columns is of the structure `[ [ ], [ ] ]`, but I would rather have it as `[ ]` since I want a container to have only one child. How would I go about with this? Is this possible in the current implementation?

**Comment by marceljuenemann** [comment]
See http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced for a demo where containers have only one "column" of children. The directive is pretty much agnostic to your model structure, you just have to give it an array.

**Comment by thiagosoeiro** [comment]
Can  you help me with this topic: #312 
It's somehow related.

**Comment by erperejildo** [comment]
> See http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/advanced for a demo where containers have only one "column" of children. The directive is pretty much agnostic to your model structure, you just have to give it an array.

that's ok for a normal list but what about if we have a nested one?
