### ISSUE TITLE
IE 9 issue if droped outside drag area.

### ISSUE THREAD

**Issue by stripathix** [marceljuenemann/angular-drag-and-drop-lists#62]
In IE9 if you drag any element and drop it outside drop area then it will disappear from the list. Like if it is been removed from the array.

Try this demo URL in IE9 http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/simple

**Comment by picosviluppo** [comment]
Same issue in Firefox 39

**Comment by marceljuenemann** [comment]
I think this is the same problem as #21, will be fixed in the next release
