### ISSUE TITLE
What am I missing on the move callback ? 

### ISSUE THREAD

**Issue by vautrinr** [marceljuenemann/angular-drag-and-drop-lists#66]
Hello All,

Great job for the dnd list ! It looks awesome. I am facing a new problem... Where I need your help : 
<li ng-repeat='answer in answers.values track by $index'
        dnd-draggable="answer"
        dnd-moved="form.move($index)"
        dnd-effect-allowed="move"
        dnd-selected="form.selected = item"
        ng-class="{'selected': form.selected === item}"
        dnd-disable-if="answers.values.length < 2">
      {{ $index + answer.value}}  
  </li>
The basic move function is answer.splice(index,1);
This is my basic dnd list.
The ouput is 
- 0 model test
- 1 test
- 2 another test

When I drag 2 to 0 I have : 

- 0 another test
- 1 test
- 2 another test

Kind of weird, isn't it ? 
Where could this come from ?

Regards, 
Rémi

**Comment by Evotica** [comment]
Can you show the whole dnd-list contents of your code?
What you have written above contains both "item" and "answer"

I had similar problem that seemed to occur when the list was an array of strings, not an array of objects and i tried to use track by $index for ng-repeat.
Moving items down seemed to work, but moving them up copied the value over the target position.

Like this:
```
            <div ng-repeat="(listName, list) in models.lists" class="col-md-6">
                <div class="panel panel-info">
                    <div class="panel-heading">
                        <h3 class="panel-title">List {{listName}}</h3>
                    </div>
                    <div class="panel-body">
                        <!-- The dnd-list directive allows to drop elements into it.
                             The dropped data will be added to the referenced list -->
                        <ul dnd-list="list">
                            <!-- The dnd-draggable directive makes an element draggable and will
                                 transfer the object that was assigned to it. If an element was
                                 dragged away, you have to remove it from the original list
                                 yourself using the dnd-moved attribute -->
                            <li ng-repeat="item in list"
                                dnd-draggable="item"
                                dnd-moved="list.splice($index, 1)"
                                dnd-effect-allowed="move"
                                dnd-selected="models.selected = item"
                                ng-class="{'selected': models.selected === item}"
                                >
                                {{$index}}{{item}}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
```
and 

```
<script>
var app = angular.module('demo', ['dndLists']);
app.controller("SimpleDemoController", function($scope) {

    $scope.models = {
        selected: null,
        lists: {"A": [], "B": []}
    };

    // Generate initial model
    for (var i = 1; i <= 3; ++i) {
        $scope.models.lists.A.push("Item A" + i);
    }

    // Model to JSON for demo purpose
    $scope.$watch('models', function(model) {
        $scope.modelAsJson = angular.toJson(model, true);
    }, true);
});
</script>
```

With that, moving list A items down caused them to move down, but with console error
Error: [ngRepeat:dupes]
Moving up gave the same error, but without moving the item.

After googling for the error, I "fixed" that by changing line

```
                            <li ng-repeat="item in list"
```
to

```
                            <li ng-repeat="item in list track by $index"
```

After that moving list A items down worked fine without errors, but moving up caused the item to overwrite target position, like in your case.

Changing list model to an array of objects {label : "stringvalue"}

```
    // Generate initial model
    for (var i = 1; i <= 3; ++i) {
        $scope.models.lists.A.push({label: "Item A" + i});
    }
```

, and using 
```
                            <li ng-repeat="item in list"
                                dnd-draggable="item"
                                dnd-moved="list.splice($index, 1)"
                                dnd-effect-allowed="move"
                                dnd-selected="models.selected = item"
                                ng-class="{'selected': models.selected === item}"
                                >
                                {{$index}}{{item.label}}
                            </li>
```
seemed to work fine. Maybe some of that was related to your problem.

**Comment by vautrinr** [comment]
Okay so it works fine !! I replaced 
li ng-repeat='item in list tracked by $index' by li ng-repeat='item in list' 
and 
model.A = [{''}];
by
model.A = [{label1:'',_index:0}];
And all works !!
Thanks you !! 

Awesome job

**Comment by mihnutzen** [comment]
track by $index is making DND duplicate the items
