### ISSUE TITLE
Any way to support touch for this library?

### ISSUE THREAD

**Issue by zman13** [marceljuenemann/angular-drag-and-drop-lists#67]

**Comment by DOrlov77** [comment]
+1

**Comment by dovy** [comment]
+1

Best by far, but needs touch.

**Comment by marceljuenemann** [comment]
Unfortunately, HTML5 drag & drop is not supported on mobile devices. You can try to get it running with some polyfill: http://stackoverflow.com/a/21351916/1620264

If touch devices are a requirement for you, I'd suggest using JavaScript drag & drop, e.g. https://github.com/angular-ui-tree/angular-ui-tree

**Comment by Bakirelived** [comment]
is this still a problem? Could it be implemented now?

**Comment by marceljuenemann** [comment]
The mobile browsers won't change anytime soon. You can either use a different library or try a shim, see https://github.com/marceljuenemann/angular-drag-and-drop-lists#supported-browsers
