### ISSUE TITLE
How do I fix: Dragging tabs horizontally 

### ISSUE THREAD

**Issue by michaelbdavidson7** [marceljuenemann/angular-drag-and-drop-lists#69]
When I'm dragging a tab in a horizontal list of tabs, instead of adding a placeholder tab within the list of tabs, dnd adds an li bullet above or below the list of tabs, which add the tab to either the front of the list or the second position in the list. Has anyone encountered this? What is creating those bullet points when I don't have an li involved at all? Thanks.
I'm using angular bootstrap tabs. 
Here's the mockup:

     tabset class="tab-container" dnd-list="layout.tabs">
            <tab
                 ng-repeat="tab in layout.tabs"
                 active="tab.active"
                 dnd-draggable="tab"
                 dnd-moved="layout.tabs.splice($index, 1)"
                 dnd-effect-allowed="move"
                 dnd-selected="layout.tabs.selected = tab"
                 tab-highlight>
                <tab-heading id="tab-draggable">
                    <span>{{tab.title}}</span> <i class="glyphicon glyphicon-remove" ng-click="removeTab($event, $index)"></i>
                </tab-heading>

**Comment by michaelbdavidson7** [comment]
The issue was with the Angular-UI Bootstrap tabs I was using, they have an isolated scope and therefore cannot be touched by the outside scope. I simply redid the tabs and I could drag and drop mostly normally, though its not perfectly horizontal yet..

**Comment by marceljuenemann** [comment]
The li element is the placeholder, so this problem could be solved by https://github.com/marceljuenemann/angular-drag-and-drop-lists/issues/77

Otherwise this seems to be working.
