### ISSUE TITLE
Incorrect dragOver and drop behavior while limited range of list.

### ISSUE THREAD

**Issue by redyyu** [marceljuenemann/angular-drag-and-drop-lists#71]
This is my case:

1. I have a menu tree with 2 level (containers), top level limited 3 parents, each item has child  with 5 limited.
2. I using 'dragoverCallback' to track back item should or should not drop intro the container. 
3. I send current drag area's 'list' intro dragover callback as param
4. When try drag a parent into children area already full, the call back got correct report, but still can 
*drop in*. (there is no placeholder showing up anymore) which mean is I can still drop in even the placeholder is disappear away and the console.log report is confirmed.
5. I had to have use a global key pass to dropCallback make sure the it's able to drop in.

The point, I believe it's not suppose doing that way, if dragover tell not droping, should not droping.
it's looks like try to droping but not able to then rollback to some how.

**Comment by marceljuenemann** [comment]
I can't reproduce that. For example, in the advanced demo the item is not allowed to be dropped in the first position according to the dragover callback, and I'm not able to trigger a drop event.

Also, an easier way to achieve what you want to do would be dnd-disable-if and check the list length there.

**Comment by redyyu** [comment]
In my case I working on a menu tree. 
1. You can drag and drop items between different levels. 
2. Each level will have total numbers item limit of each level. 
3. Even its reach the limit stall can drag and drop to switch orders in same level.

so I guess dnd-dsiabled-if might not working on this case because it's just can't drop to another level, not can't drag / drop at all.  Its depend what you start drag  and where you want to drop.

The problem is not reach the limit or not. Is the fallback action after drop is rejected.
I found the dragging item will automatically pop to another drop able point ( it might be the last place of placeholder)  while drop is failed.

Anyway, I did fix it by using fixed placeholder's size. (if the placeholder is not same size in different level the drag point might change to the place you are not except. because the DOM is changing.)

I can reproduce it any time. I can write a demo for it after this month if you need.

ps: I know the adv demo is disabled drop to the first item is on purpose, but infect confused lot people with that, it's will better/nice to have different demo show major options.

**Comment by fffuture** [comment]
I have same issue when set limit for list.

If remove item from list, it can be dropped into void, and disappear (but you can swap elements in one list).

[Fiddle](https://jsfiddle.net/3uya8jvL/)
