### ISSUE TITLE
"[$injector:nomod] http://errors.angularjs.org/1.2.16/$injector/nomod?p0=demo"

### ISSUE THREAD

**Issue by i3lackstorm** [marceljuenemann/angular-drag-and-drop-lists#72]
I am trying to use the simple demo. I put ng-app="demo" in the body tag and add resources for angular.min.js and your angular-drag-and-drop-lists.js

But, i get the error ("[$injector:nomod] http://errors.angularjs.org/1.2.16/$injector/nomod?p0=demo") in firefox when i try to debug the angular.module("demo").controller("SimpleDemoController", function($scope) {

and more error afterward:
rror: [$injector:modulerr] http://errors.angularjs.org/1.2.16/$injector/modulerr?p0=demo&p1=%5B%24injector%3Anomod%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.2.16%2F%24injector%2Fnomod%3Fp0%3Ddemo%0At%2F%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.16%2Fangular.min.js%3A6%3A450%0AYc%2Fb.module%3C%2F%3C%2Fb%5Be%5D%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.16%2Fangular.min.js%3A20%3A260%0AYc%2Fb.module%3C%2F%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.16%2Fangular.min.js%3A20%3A1%0Ae%2F%3C%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.16%2Fangular.min.js%3A33%3A1%0Aq%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.16%2Fangular.min.js%3A7%3A278%0Ae%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.16%2Fangular.min.js%3A32%3A445%0Aac%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.16%2Fangular.min.js%3A36%3A34%0A%24b%2Fc%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.16%2Fangular.min.js%3A17%3A431%0A%24b%40http%3A%2F%2Fajax.googleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.2.16%2Fangular.min.js%3A18%3A140%0AWc%40http%3A%2F

please tell me what i did wrong

**Comment by ajmajma** [comment]
Make sure you are bootstrapping and injecting with angular correctly, this error just means you don't have your injection modules set up correctly.
