### ISSUE TITLE
Suggestions for dragging configuration.

### ISSUE THREAD

**Issue by artgryn** [marceljuenemann/angular-drag-and-drop-lists#73]
1. **Add drag icon/area**
**Example:** I want drag  a list item but it should be possible to pick item for dragging only from some icon or area. 
**Usage:** currently if item draggable it possible to pick this item for dragging from any point on this item which makes impossible to copy some data from this item 

2. **Limit dragging area**
**Example:** Pick up some item in a list for dragging and limit user to move this item only vertically without going out of allowed area.
**Usage:** some situations requires when user should be possible move item only inside list. Now you can drag item at any place of the screen which is not a problem because item will go back to current list if you will try to drop item in a wrong place. **Simply** do not allow user drag item out of allowed area.

**Comment by mcgilly17** [comment]
+1, This would be excellent. You cannot currently select any text within an input for example without incurring a drag.

**Comment by delachi** [comment]
+1, I also will like to to see the 'Limit dragging area' functionality.  I want to disallow dragging outside of a area.

**Comment by cmlenz** [comment]
1. is covered by my PR #48 (see also issue #31)

**Comment by delachi** [comment]
Hi @cmlenz , I looked at your PR #48 and issue #31, but I don't see the functionality that prevents a user from dragging outside of a container.  I'm looking to prevent dragging of an item outside the container, but still allow the item to sorted.

**Comment by marceljuenemann** [comment]
Thanks for the suggestions. Unfortunately, native drag & drop does not allow you to limit the area for dragging, you can even drag outside the browser window.

Number 1 is a duplicate.
