### ISSUE TITLE
ignore list for element you want drag in side a drag drop container 

### ISSUE THREAD

**Issue by redyyu** [marceljuenemann/angular-drag-and-drop-lists#74]
etc., A input might in side drag container but when you point intro input filed you wont trigger drag.
can you add some attribute for child element skip drag drop.

**Comment by marceljuenemann** [comment]
Can you try setting pointer-events: none in CSS?

**Comment by redyyu** [comment]
No I can't. That will break other js frameworks events flow. Etc., angular material.

**Comment by marceljuenemann** [comment]
Duplicate of #57, will be fixed in next release

**Comment by redyyu** [comment]
Thank you very much, can wait. :)
