### ISSUE TITLE
Need to save every time an item is dragged

### ISSUE THREAD

**Issue by crisoberillo** [marceljuenemann/angular-drag-and-drop-lists#76]
Is there a way I can save the list every time the drag is complete?
I tryed to catch a 'dragend' event without success. I'm only able to catch a 'drop' event, but when it fires, the list is not changed yet.

To achieve the catch of 'drop' event I created a new attribute directive and in his link function I do:
```
element.bind('drop', function () {
    $rootScope.$emit('DROP-EVENT');
});
```
In my controller:
```
$rootScope.$on('DROP-EVENT', function () {
    console.log("DROP-EVENT fired:", $scope.list); //instead of $scope.save(); just for debug
});
```

Anyone knows a solution?

**Comment by graywolf336** [comment]
A temporary solution you could do is use `$timeout` to run the next tick and the list should be changed then. I used that in my project and haven't had an issue so far that I can tell..

**Comment by marceljuenemann** [comment]
Maybe I'm missing something, but wouldn't the angular way of implementing this be $watchCollection?

**Comment by graywolf336** [comment]
It might be one of the options, but I think having another event fire off after the array/list is updated would be preferable and in the same theme as the rest of the module.

**Comment by crisoberillo** [comment]
I agree with graywolf336, but I have to say I didn't know of the existence of $watchCollection. Now I explain why sometimes it didn't work.
Thanks for your answers :)

**Comment by marceljuenemann** [comment]
$watchCollection solves this and also works for changes from other parts of the code, so I don't want to add yet another callback for this. If you want to be a tiny bit more efficient you can do a $timeout with 0ms in the drop callback, that will work as well.
