### ISSUE TITLE
custom element for placeholder

### ISSUE THREAD

**Issue by AxxlForce** [marceljuenemann/angular-drag-and-drop-lists#77]
maybe I'm missing something, but I'm searching for a way to use my own element as a placeholder. I know that I can overwrite it's style via CSS but I'm looking for a way to provide my own HTML for it.

**Comment by addykim** [comment]
Not sure if this will work but if you don't need the default placeholder, try changing the the line 215 of the .js file:
`var placeholder = angular.element("<li class='dndPlaceholder'></li>");`

I think as long as you give your element the class dndPlaceholder and/or give it the property `position: relative;` it might work.

**Comment by marceljuenemann** [comment]
For simple cases the CSS content property might help: http://www.w3schools.com/cssref/pr_gen_content.asp

But I guess it's a valid feature request. It could be implemented by looking for an existing element with the dndPlaceholder, and only creating a new li if such an element does not exist.

**Comment by Blaze34** [comment]
When new release will be available?
