### ISSUE TITLE
Dragging item into text field drops the json representation of the item into the field

### ISSUE THREAD

**Issue by joshuadmatthews** [marceljuenemann/angular-drag-and-drop-lists#80]
You can try this on any of the sample pages ,just drag an element into the browsers address bar and you see it pasted the json representation of that elements model into the address bar.

**Comment by marceljuenemann** [comment]
Unfortunately, Internet Explorer only supports the text/plain mime type when dragging, therefore this happens. If you don't care about IE, you could change the mime type to something custom to avoid this problem.
