### ISSUE TITLE
Select multiple items with ctrl or by mouse selection area

### ISSUE THREAD

**Issue by joni2back** [marceljuenemann/angular-drag-and-drop-lists#82]
I wish to use this library but I cannot find the feature to select multiple items with CTRL+Click .. or with mouse cursor...
Would be implemented?

**Comment by marceljuenemann** [comment]
HTML5 doesn't really provide a good way to drag multiple items, but there seem to be ways to implement it: http://www.sitepoint.com/accessible-drag-drop/

However, I guess it would be a major change to the library, for starters it would need a concept of selecting items. It's also unclear how selection would work together with nested lists or how you determine which items may be selected together if you have multiple lists.

**Comment by marceljuenemann** [comment]
Looking into this, there is no way to drag multiple elements with HTML5. It might be possible to somehow pass the information about the other selected elements with the dragged one, but I don't see how this would work with nested lists, so its out of scope of this library. You might be more lucky with a pure jQuery drag & drop library.

**Comment by joni2back** [comment]
Ok.. I was thinking and testing the best way to implement this in any app.. and should be
```c
{
  elements: [selected1, selected2],
  action: {
    name: "add",
    target: parent.list5
  }
}
```
processing each file (foreach elements) with the action

**Comment by gkohen** [comment]
Is there a reason why this issue has been closed? Do we not even consider implementing it?

**Comment by renatodv** [comment]
Yeah on HTML5 there's no way, I just spent a week creating custom code to achieve this in pure javascipt and jquery.
