### ISSUE TITLE
Dragging into an empty list

### ISSUE THREAD

**Issue by JohannMarx** [marceljuenemann/angular-drag-and-drop-lists#84]
Hi Marcel,

Thank you very much for this awesome piece of code! It's working really well, except for one minor issue:

I have a source list and a target list. The target list can be empty and the code does not allow me to drag the item onto the target list if there are no items in it.

Is this by design or am I missing something?

Thanks again for your hard work on this - it's really appreciated!

Thanks,
Johann.

**Comment by herrherrmann** [comment]
It's probably not working because your empty target list has a **height of 0**. Just force some height through CSS in order to make it appear and droppable:
```css
.target-list {
  min-height: 30px;
}
```

**Comment by JohannMarx** [comment]
Hi Sebastian,

 

That makes sense thanks, I’ll give it a shot. Thanks again for the awesome code, you saved me a lot of time and frustration.

 

Thanks,

Johann.

**Comment by herrherrmann** [comment]
You're welcome! Enjoy using these cool directives.
