### ISSUE TITLE
drag element cropped if originally out of view

### ISSUE THREAD

**Issue by twmulloy** [marceljuenemann/angular-drag-and-drop-lists#85]
If an item is out of view `overflow-y: auto;` before dragging, all of the element that is out of sight gets cropped out. 

![screen shot 2015-07-06 at 5 33 41 pm](https://cloud.githubusercontent.com/assets/330435/8536495/076d0a92-2407-11e5-9676-100cbd6c9e28.png)

appears to be happening in chrome but not firefox (mac)  so possibly a bug with chrome html5 drag element rendering

**Comment by marceljuenemann** [comment]
Interesting, but as you said this is entirely browser behaviour, nothing we can do about it.
