### ISSUE TITLE
dnd-drop prevents dnd-moved from firing

### ISSUE THREAD

**Issue by thardy** [marceljuenemann/angular-drag-and-drop-lists#86]
I had the dnd-moved callback working just fine on the li, until I added dnd-drop to the ul...

```
<ul dnd-list="model.visibleColumns" dnd-drop="model.droppedInVisible(event, index, item)">
    <li ng-repeat="col in model.visibleColumns" dnd-draggable="col" dnd-moved="model.movedFromVisible($index)">
        {{col.name}}
    </li>
</ul>
```

...now my moved callback never gets called.  Here's my drop callback...

```
function droppedInVisible(event, index, item) {
    item.visible = true;
    return item;
}
```

When I change the drop callback to the following...

```
function droppedInVisible(event, index, item, external) {
            item.visible = true;

            if (external) {
                return false;
            }
            return item;
        }
```

I get the same behavior.  The value of external is always false.  Not sure why that is.

**Comment by marceljuenemann** [comment]
Are you sure that you callback is actually called? Sounds like setting some breakpoints and debugging could give you some insights here. You're not passing anything as fourth argument, so external should always be undefined.

**Comment by santialbo** [comment]
I'm having the same issue here, when I use dnd-drop to insert the item myself in the collection, dnd-moved (which I was using to remove the item from the collection, and works when I dont add the dnd-drop attribute) doesn't fire.

**Comment by santialbo** [comment]
I actually read more carefully the sourcecode, it seems that dnd-drop is not meant to be the one inserting the element in the collection since it's being inserted afterwards anyway:

```
        if (attr.dndDrop) {
          transferredObject = invokeCallback(attr.dndDrop, event, transferredObject);
          if (!transferredObject) {
            return stopDragover();
          }
        }

        // Retrieve the JSON array and insert the transferred object into it.
        var targetArray = scope.$eval(attr.dndList);
        scope.$apply(function() {
          targetArray.splice(getPlaceholderIndex(), 0, transferredObject); ///<------------------------------
        });
```
I think it would be useful if there was a way to replace the default behaviour, (maybe dnd-insert that defaults to a function that inserts the element in the collection)

**Comment by marceljuenemann** [comment]
What's your use case for wanting to do the insert yourself? Maybe it helps that there is now a dnd-inserted callback, which you could use to modify the item after it was inserted.

**Comment by PloughingAByteField** [comment]
In my case flexibility, my lists are not created equal ;). 
Due to the data I am working with a straight insert is not going to work and I do not like the idea of post modification. The drop function is where I need to to doing list manipulation such as constructing an object of the correct type if the dropped item contains only a subset of the data and modifying all the data items below the drop point.
Yes all that can be done with what is there but you have succeeded in writing very easily maintainable code. 
So I have done this (called it dndInserter for lack of a better term)
        var targetArray = scope.$eval(attr.dndList);
        if (attr.dndInserter) {
            invokeCallback(attr.dndInserter, targetArray, event, index, transferredObject);
        } else {
            // Retrieve the JSON array and insert the transferred object into it.
            scope.$apply(function() {
              targetArray.splice(index, 0, transferredObject);
            });
        }
        invokeCallback(attr.dndInserted, event, index, transferredObject);

And 
dnd-list="assignedToRace" dnd-inserter="insertEvent(assignedToRace, event, index, item)"

and surprise, no-op'ed the insertion, of course I have the option of doing something here but I like having the choice
$scope.insertEvent = function(target, event, index, item) {
        // no-op
    };

I let drop do all the work, much more concise and will be easier to write jasmine tests.

**Comment by marceljuenemann** [comment]
From 1.4.0 you can now return true in dnd-drop to tell the directive that you will take care of the insertion yourself.

**Comment by shenrichs** [comment]
I'm getting the same behavior.  When I add attribute to the enclosing <ul>, the dnd-moved events on the child <li> elements do not fire.  If I remove the dnd-drop attribute, everything works fine.

![capture](https://cloud.githubusercontent.com/assets/10523676/13784567/044f8824-ea8d-11e5-9b03-5dd3680de9ee.PNG)

**Comment by moLirik** [comment]
+1

**Comment by moLirik** [comment]
@shenrichs this is because of [#297](https://github.com/marceljuenemann/angular-drag-and-drop-lists/issues/297)

**Comment by kapil708** [comment]
i have the same issue so i use code of advance move
<div class="col-md-2" ng-repeat="(key,val) in LeadList">
                                <div class="panel panel-default"
                                     dnd-list="val"
                                     dnd-allowed-types="['item']"
                                     dnd-horizontal-list="true"
                                     dnd-external-sources="true"
                                     dnd-effect-allowed="all"
                                     dnd-drop="dropCallback(key, item)">
                                    <div class="panel-heading">
                                        <h6 class="panel-title">{{key}}</h6>
                                    </div>
                                    <div class="panel-body p-5" style="background:#F5F8FA">
                                        <ul class="media-list">
                                            <li class="media bg-white p-5" ng-repeat="item in val"
                                                dnd-draggable="item"
                                                dnd-type="'item'"
                                                dnd-effect-allowed="all"
                                                dnd-moved="val.splice($index, 1)"
                                                style="border-radius: .1875rem; box-shadow: 0 1px 5px 0 rgba(45,62,80,.12);">
                                                <div class="media-body">
                                                    <table class="table table-borderless">
                                                        <tr>
                                                            <td class="no-padding p-5">
                                                                <div class="media-body">
                                                                    <div class="media-heading">
                                                                        <b>{{item.Name}}</b><br />
                                                                        {{item.Mobile}}<br />
                                                                        {{item.Employee}}
                                                                        @*<img src="assets/images/demo/users/face24.jpg" class="img-circle img-xs" alt="">*@
                                                                    </div>
                                                                </div>
                                                            </td>
                                                            <td class="no-padding">
                                                                <a href="#"><i class="icon-price-tags"></i></a>
                                                                <a href="#"><i class="icon-notebook"></i></a>
                                                                <a href="#"><i class="icon-task"></i></a>
                                                                <a href="#"><i class="icon-folder-open2"></i></a>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

**Comment by kapil708** [comment]
i have the same issue so i use code of advance move
`<div class="col-md-2" ng-repeat="(key,val) in LeadList">
                                <div class="panel panel-default"
                                     dnd-list="val"
                                     dnd-allowed-types="['item']"
                                     dnd-horizontal-list="true"
                                     dnd-external-sources="true"
                                     dnd-effect-allowed="all"
                                     dnd-drop="dropCallback(key, item)">
                                    <div class="panel-heading">
                                        <h6 class="panel-title">{{key}}</h6>
                                    </div>
                                    <div class="panel-body p-5" style="background:#F5F8FA">
                                        <ul class="media-list">
                                            <li class="media bg-white p-5" ng-repeat="item in val"
                                                dnd-draggable="item"
                                                dnd-type="'item'"
                                                dnd-effect-allowed="all"
                                                dnd-moved="val.splice($index, 1)"
                                                style="border-radius: .1875rem; box-shadow: 0 1px 5px 0 rgba(45,62,80,.12);">
                                                <div class="media-body">
                                                    <table class="table table-borderless">
                                                        <tr>
                                                            <td class="no-padding p-5">
                                                                <div class="media-body">
                                                                    <div class="media-heading">
                                                                        <b>{{item.Name}}</b><br />
                                                                        {{item.Mobile}}<br />
                                                                        {{item.Employee}}
                                                                        @*<img src="assets/images/demo/users/face24.jpg" class="img-circle img-xs" alt="">*@
                                                                    </div>
                                                                </div>
                                                            </td>
                                                            <td class="no-padding">
                                                                <a href="#"><i class="icon-price-tags"></i></a>
                                                                <a href="#"><i class="icon-notebook"></i></a>
                                                                <a href="#"><i class="icon-task"></i></a>
                                                                <a href="#"><i class="icon-folder-open2"></i></a>
                                                            </td>
                                                        </tr>
                                                    </table>
                                                </div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>`
