### ISSUE TITLE
Problem dropping items

### ISSUE THREAD

**Issue by Padwah** [marceljuenemann/angular-drag-and-drop-lists#91]
I'm new to angular and I'm trying to utilise your drag and drop directive with a demo project as a learning exercise. I have a web service that returns a `Board` object that contains an array of `Stacks` with each stack containing an array of `Cards`, my controller calls the webservice and adds a returned board to the model and then the view binds each `Stack` and its array of `Card` to a new list. My problem is that when I drag a card from one stack to another I get the error `targetArray.splice is not a function`

This is the data returned by the web service
```
{
	"Id":1,
	"Name":"General Work",
	"Stacks":[
		{
			"Id":1,
			"Name":"Planning",
			"Cards":[]
		},
		{
			"Id":2,
			"Name":"In Progress",
			"Cards":[
				{
					"Id":2,
					"Name":"CRM",
				},
				{
					"Id":1,
					"Name":"POAS Updates",
				}
			]
		},
		{
			"Id":3,
			"Name":"Completed",
			"Cards":[
				{
					"Id":3,
					"Name":"Something Else",
					"Description":null
				}
			]
		}
	]
}
```
This is the controller
```javascript
angular.module('ListApp.controllers', []).controller('ListController', function ($scope, boardService) {
    boardService.getBoard().success(function (response) {
        $scope.board = response;
    });
});
```
And this is the binding part of my view
```html
<div ng-repeat="stack in board.Stacks" class="col-md-4">
	<div class="panel panel-info">
		<div class="panel-heading">
			<h3 class="panel-title">{{stack.Name}}</h3>
		</div>
		<div class="panel">
			<ul dnd-list="stack">
				<li ng-repeat="card in stack.Cards"
					dnd-draggable="card"
					dnd-effect-allowed="move">
					{{card.Name}}
				</li>
			</ul>
		</div>
	</div>
</div>
```
Anybody got any idea where I'm going wrong?

**Comment by marceljuenemann** [comment]
Try dnd-list="stack.Cards" instead of dnd-list="stack"

**Comment by Padwah** [comment]
Awesome, cheers :)
