### ISSUE TITLE
ng-init index variable not staying in sync with $index

### ISSUE THREAD

**Issue by tajohnson661** [marceljuenemann/angular-drag-and-drop-lists#92]
I'm trying to use drag and drop to move objects around in the same list.  Within the list, I have a sublist, so I'm using nested ng-repeats.  In the first ng-repeat, I'm doing something like:

<li ng-repeat="item in list" ng-init="x = $index" dnd-draggable="item" ...

It seems that after I drop the object, "x" is no longer in sync with $index.  I would think they would be exactly the same, or basically ng-init is useless.  And I can't use $index directly since I have another ng-repeat elsewhere within the tree.

Thoughts?  Thanks!

**Comment by tajohnson661** [comment]
A little more information here... I thought I could solve it by adding "track by $index" in the ng-repeat.  That seemed to solve the sync issue I mentioned, but then the index being passed to the dnd-moved callback was off if I moved an item to earlier in the dropzone list.  I feel like there might be a workaround for this situation, but I can't come up with one yet.

**Comment by marceljuenemann** [comment]
Well, ng-init is only triggered once on initialization, so it does not update x when elements are moved around. I see many ways around this, e.g. use $parent.$index in the child scope, or just call list.indexOf(item).
