### ISSUE TITLE
Include origin and destination of item being dragged in dnd-drop callback.

### ISSUE THREAD

**Issue by gurgus** [marceljuenemann/angular-drag-and-drop-lists#93]
I imagine this is a feature request, rather than an issue.

Basically I have the use case of the following:
* I have two lists (A and B)
* I want to be able to drag items in list A to list B
* I want to be able to drag items in list B to list A
* I want to be able to reorder items in list A
* I want to be able to reorder items in list B
* For each of the 4 drag operations I have mentioned, I want to know where the element is being dragged from and where it is being dropped to

For the reordering operations, this is easy to detect with no changes to the angular-drag-and-drop-lists library. You can simply iterate over the list in the dnd-drop callback and if *item* is already in the list, then you know that the source list and destination list are the same. The tricky part is detecting that the source and destination list are different.

I imagine this could be made possible by modifying the dnd-drop callback to include this information.

If anyone has got any ideas I'd be keen to hear!

-Dave

**Comment by marceljuenemann** [comment]
Why do you want to do this? It sounds like better software design to me if all lists are independent and just care about their content, not about other lists.

To detect whether an element came from a different list, can't you just look at the length of the list before and after? If it came from a different one, the length should have been incremented.

**Comment by guizero** [comment]
+1... I am talking to my server and one of the crucial information is the list id (or any other info) of where the item was dropped. For example, I want to make a http call sending a request for the server to update to which list the item belongs. Any better ideas on how to do that?

**Comment by gurgus** [comment]
Hey Marcel,

Thanks for getting back to me.

I'll try to answer your question of why someone would want to do this as clearly as I can. Please let me know if any ambiguity still exists.

I like your library, but at the moment it is not easy to know at the time of a drop event where an element came from, have access to that item, and know where the object came from.

In my opinion, it seems like it is less intuitive to not know where an item came from. With that simple piece of information, you can start to do some more complex stuff (which is what I'm looking to build at the moment). Because of the this, I'm being forced to use RubaXas's Sortable library (https://github.com/RubaXa/Sortable). Sortable is incredibly powerful in terms of the events you can react to (see the options section in the readme), but is far more cumbersome to develop with. To get a feel for the sorts of things you can do with Sortable, check out this bin: http://jsbin.com/weteyugogi/edit?html,js,console,output

Let me know your thoughts on it all. Sorry if I come across in an arrogant tone - it isn't intended, but at the moment I can't see the feature parity between the events you can observe between these two libraries.

-Dave

**Comment by marceljuenemann** [comment]
Thanks for your explanation, doesn't sound arrogant at all. I understand *what* you want to do, but I don't see *why* you want to do it from a software design point of view. Why do you care where the element came from? Why not have both lists take care of whatever logic they have to do for themselves?

Anyways, the only way to implement this is with global state, and you can do that yourself with the dnd-dragstart callback. Although that does not work across browser tabs (dnd-external-sources).

**Comment by dowlingw** [comment]
Ooh, this would be useful. If `dnd-drop` is a cancellable event (which it is from my reading) - then this would be useful information to have to evaluate cancellation rules.

Example scenario: The user isn't allowed to drag the item from the "Done" column to the "In Progress" column.

If it's information already being used by the drag and drop mechanism, providing it to the hook makes more sense than requiring any caller to check each list. O(1) vs O(N).

**Comment by marceljuenemann** [comment]
> If it's information already being used by the drag and drop mechanism

Unfortunately, it is not. With native drag and drop the operation goes through the operating system's drag and drop mechanism, which does not provide information on where it came from.

One solution to your example would be to use dnd-type and dnd-allowed-types, like in this [demo](http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/types).

**Comment by dowlingw** [comment]
Allowed types are a good solution for rules with a single constraint, but could fall over with more complex requirements - which is why I feel this is a valuable feature.

HTML5 drag and drop does support transferring data, which can be populated when the dragEvent fires on the source, and can be retrieved from the dropEvent:

https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Drag_operations#drop

Whilst putting a list reference into there isn't feasible, supporting some kind of source list identifier in the directive for a source tag or some other textual identifier would be _super_ handy.

Eg:

    <ul dnd-list="list" dnd-tag="list1"> .. </ul>
    <ul dnd-list="list" dnd-tag="list1"> .. </ul>

Packing the data into the event would look something like:

    event.dataTransfer.setData('text/plain', TAGVAR)

And pulling it back out on the drop event:

    var data = event.dataTransfer.getData('text/plain');

By providing the source lists tag in the `dnd-drop` callback, this allows users of the library to implement more complex business rules without complex logic.

Would you be happy to accept a pull request for this functionality? I have an immediate need for this functionality and would be happy to contribute it.

**Comment by marceljuenemann** [comment]
Well, yeah, using setData and getData is the core of what this directive already does :) Whatever you put into dnd-draggable will be serialized, so you should be able to do dnd-draggable="{tag: 'list1', data: item}" and then set the new tag in the drop callback.

**Comment by gurgus** [comment]
I think you may be missing the point here, Marcel.

There are libraries that already do this sort of thing, and yours currently doesn't. The end user can hack around and get a sort-of-working solution going, but it seems like that if this were given to the developer without them having to introduce their own complex logic, that's a huge win :)

@dowlingw asked if he provided a patch would you be happy to accept the pull request and allow this functionality in the core code - are you able to answer this? If so, I may assist him on this as (I said before) your library is less cumbersome to work with than others (albeit less flexible at the moment).

-Dave

**Comment by marceljuenemann** [comment]
I still don't see good use cases for this. The use cases given by @dowlingw are already possible to implement with dnd-type, without any logic at all.

I created [http://plnkr.co/edit/imXY0yXgl5OryBo3J50V?p=preview](this plunkr), maybe that helps. It will output stuff like "Item A1 was dragged from list C to list B" to the console.

**Comment by gurgus** [comment]
I guess the use case that I am specifically stuck with when trying to implement it with your library.

I'll elaborate on the original use case that I gave you so you will have a clearer picture of what I'm trying to achieve.

I have two lists (A and B), I need the following to happen:
* I need to be able to move items from A->B, B->A, A->A, B->B. So far, we can do this trivially (obviously, as these are basic operations).
* When dropping an item from A->B, if a certain condition is true about the item in A, a modal dialog appears and asks some questions, if the user answers no to any of these (i.e. the modal returns a falsey value), then the item should not be moved and both lists should remain exactly the same as they did before the drag operation was started. Assuming the user doesn't answer no to anything, some other items from list A may be moved along to list B with it.

I'm aware that a lot of what I have just mentioned is very specific to the work I'm doing at the moment but at the core of it there are definitely some handy features that can come out of it. i.e. cancelling a move if a callback returns a certain (i.e. falsey) value.

Keen to hear your opinions on this based on what I've mentioned. If you think this still isn't a good use case, I can respect that, but I think it is hindering more powerful uses of this library.

-Dave

**Comment by marceljuenemann** [comment]
What you want to do is super easy to do already without any hacks. Did you take a look at the plunkr I posted? It seems to do exactly what you described. With only two lists you could even just call indexOf on the list you're dropping to, to figure out if the element is already in there.

Going on vacation today, don't be surprised if I no longer reply.

**Comment by gopal757** [comment]
How can I get the index on which we are dropping an item, If we are dropping on a ui-Grid.I have gone through the dnd-callback, but not got the clear idea.Please suggest some way to capture the index from ui-grid .
