### ISSUE TITLE
Regarding first time configuration

### ISSUE THREAD

**Issue by igate821581** [marceljuenemann/angular-drag-and-drop-lists#97]
Hi,
I just installed angular drag and drop framework  also followed the steps from the readme.
but unable to see anything as there is no console error.
i also included the required js and css files and also injected the dndLists module but not able to see anything.
If possible can you show the full working demo with simple example of all the necessary injection.

**Comment by marceljuenemann** [comment]
Hey,
there are lots of demos here: http://marceljuenemann.github.io/angular-drag-and-drop-lists/demo/#/simple
