### ISSUE TITLE
Is there a way the dropzone can be something other than a container(array) ?

### ISSUE THREAD

**Issue by none-da** [marceljuenemann/angular-drag-and-drop-lists#98]
I can see that the entire API is laid out lists(arrays). Where we drop an item into an existing array. But can the dropzone be something other than a container ? So that I can replace the existing item with the dropped item.

**Comment by marceljuenemann** [comment]
You have to pass an array to dnd-list, but you can easily make sure that it only has one item, e.g. remove the existing item in the dnd-drop callback.

**Comment by none-da** [comment]
@marceljuenemann agreed :+1:

**Comment by jmls** [comment]
is there an example of this somewhere - sounds like something I may be able to use. thanks.
